sberdevices/plasma

packages/ui/src/components/Badge/Badge.mdx, packages/ui/src/components/Button/Button.mdx, packages/ui/src/helpers/ThemeBackground.tsx
closes #49, #60 
<details>
<br />
```bash
npm install demo-tokens@1.0.0-canary.63.7e5877b7c3bb8adaa6c378f24a068fccc71f3c49.0
npm install @sberdevices/plasma-tokens@1.0.0-canary.63.7e5877b7c3bb8adaa6c378f24a068fccc71f3c49.0
npm install @sberdevices/ui@1.0.0-canary.63.7e5877b7c3bb8adaa6c378f24a068fccc71f3c49.0
yarn add demo-tokens@1.0.0-canary.63.7e5877b7c3bb8adaa6c378f24a068fccc71f3c49.0
yarn add @sberdevices/plasma-tokens@1.0.0-canary.63.7e5877b7c3bb8adaa6c378f24a068fccc71f3c49.0
yarn add @sberdevices/ui@1.0.0-canary.63.7e5877b7c3bb8adaa6c378f24a068fccc71f3c49.0
```
</details>
=> Доработана документация для Button и Badge

packages/ui/src/mixins/applyMotion.ts
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.65.d13ca047d7317425bc6442fd77a3295bf12f7baa.0
yarn add @sberdevices/ui@0.21.0-canary.65.d13ca047d7317425bc6442fd77a3295bf12f7baa.0
```
</details>
=> Скалирование кнопки при действии

packages/ui/src/components/Button/ActionButton.tsx, packages/ui/src/components/Card/CardBadge.tsx
closes #12 
<details>
<br />
```bash
npm install @sberdevices/ui@0.20.1-canary.70.f1c49457a3caafb990f52c3ee04c729abff07490.0
yarn add @sberdevices/ui@0.20.1-canary.70.f1c49457a3caafb990f52c3ee04c729abff07490.0
```
</details>
=> fix(ui): Удалено свойство color, вместо view

packages/ui/src/components/Tabs/TabItem.tsx, packages/ui/src/components/Tabs/Tabs.mdx, packages/ui/src/components/Tabs/Tabs.stories.tsx, packages/ui/src/components/Tabs/Tabs.tsx, packages/ui/src/components/Tabs/index.ts, packages/ui/src/helpers/ThemeBackground.tsx, packages/ui/src/mixins/addFocus.ts, packages/ui/src/mixins/applyDisabled.ts, packages/ui/src/mixins/applyMotion.ts
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.74.82212fc4f5f280e38f2cd35b6b772fde48ed2c21.0
yarn add @sberdevices/ui@0.21.0-canary.74.82212fc4f5f280e38f2cd35b6b772fde48ed2c21.0
```
</details>
=> feat(ui): Компонент Tabs

packages/ui/src/components/TextField/TextField.stories.tsx, packages/ui/src/components/TextField/TextField.tsx
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.77.0ec2eda37ead183c14df55af1af88e4e1046eb36.0
yarn add @sberdevices/ui@0.21.0-canary.77.0ec2eda37ead183c14df55af1af88e4e1046eb36.0
```
</details>
=> feat(ui): Переработан TextField, отвязан от Input

packages/ui/src/components/Button/ActionButton.tsx, packages/ui/src/components/Stepper/Stepper.mdx, packages/ui/src/components/Stepper/Stepper.stories.tsx, packages/ui/src/components/Stepper/Stepper.tsx
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.75.0c6fe17862aac6a4f2a715544d3dbb45b10d864e.0
yarn add @sberdevices/ui@0.21.0-canary.75.0c6fe17862aac6a4f2a715544d3dbb45b10d864e.0
```
</details>
=> feat(ui): Размер xs для Stepper

packages/ui/src/components/Badge/Badge.mdx, packages/ui/src/components/Badge/Badge.stories.tsx, packages/ui/src/components/Badge/Badge.tsx, packages/ui/src/components/Card/CardBadge.tsx, packages/ui/src/components/Card/index.ts, packages/ui/src/mixins/applyView.ts
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.78.329e1724e3c0f64e22bb25198307775a5b6ab522.0
yarn add @sberdevices/ui@0.21.0-canary.78.329e1724e3c0f64e22bb25198307775a5b6ab522.0
```
</details>
=> feat(ui): Пресет quantity для Badge

packages/ui/src/components/theme.mdx
=> docs: Пример смены персонажа

packages/ui/src/components/Card/Card.stories.tsx
<details>
<br />
```bash
npm install @sberdevices/ui@0.20.1-canary.86.34827c1f3255f38a23ac8b600f6ab8c3ef52ccfe.0
yarn add @sberdevices/ui@0.20.1-canary.86.34827c1f3255f38a23ac8b600f6ab8c3ef52ccfe.0
```
</details>
=> fix(ui): Исправлена сториз card detail

packages/ui/src/components/Button/ActionButton.tsx, packages/ui/src/components/Button/Button.tsx, packages/ui/src/hocs/hocs.mdx, packages/ui/src/mixins/applyView.ts, packages/ui/src/mixins/mixins.mdx, packages/ui/src/utils/index.ts, packages/ui/src/utils/mediaQuery.ts, packages/ui/src/utils/roundness.ts, packages/ui/src/utils/utils.mdx
<details>
<br />
```bash
npm install @sberdevices/ui@0.20.1-canary.88.6190da8890d3173afec8421201902829263e4696.0
yarn add @sberdevices/ui@0.20.1-canary.88.6190da8890d3173afec8421201902829263e4696.0
```
</details>
=> Документация и рефакторинг для mixins, hocs, utils

README.md
Поправить ссылку на storybook
cc @LamaEats
=> TRIVIAL — Update README.md

packages/ui/src/components/Badge/Badge.tsx, packages/ui/src/components/Skeleton/LineSkeleton.tsx, packages/ui/src/components/Skeleton/RectSkeleton.tsx, packages/ui/src/components/Skeleton/Skeleton.mdx, packages/ui/src/components/Skeleton/Skeleton.stories.tsx, packages/ui/src/components/Skeleton/Skeleton.tsx, packages/ui/src/components/Skeleton/TextSkeleton.tsx, packages/ui/src/components/Skeleton/index.ts, packages/ui/src/components/Typography/typography.mdx, packages/ui/src/hocs/hocs.mdx, packages/ui/src/hocs/index.ts, packages/ui/src/hocs/withSkeleton.tsx, packages/ui/src/index.ts, packages/ui/src/mixins/applyRoundness.ts, packages/ui/src/mixins/applySkeletonGradient.tsx, packages/ui/src/mixins/index.ts, packages/ui/src/mixins/mixins.mdx
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.84.61794b7ecb327f8463810d1f7d09074acfab392b.0
yarn add @sberdevices/ui@0.21.0-canary.84.61794b7ecb327f8463810d1f7d09074acfab392b.0
```
</details>
=> feat(ui): Набор компонентов Skeleton

packages/ui/.storybook/preview.js, packages/ui/package.json, packages/ui/src/components/Card/Card.stories.tsx, packages/ui/src/components/Card/Card.tsx, packages/ui/src/components/Carousel/Carousel.mdx, packages/ui/src/components/Carousel/Carousel.stories.tsx, packages/ui/src/components/Carousel/Carousel.tsx, packages/ui/src/components/Carousel/CarouselWrapper.tsx, packages/ui/src/components/Device/DeviceDetection.tsx, packages/ui/src/components/Device/index.ts, packages/ui/src/components/Grid/Col.tsx, packages/ui/src/components/Grid/Container.tsx, packages/ui/src/components/Header/Header.stories.tsx, packages/ui/src/components/Header/Header.tsx, packages/ui/src/components/Header/HeaderBack.tsx, packages/ui/src/components/Header/HeaderRoot.tsx, packages/ui/src/components/Header/HeaderTitle.tsx, packages/ui/src/components/MarkedList/MarkedList.mdx, packages/ui/src/components/MarkedList/MarkedList.stories.tsx, packages/ui/src/components/MarkedList/MarkedList.tsx, packages/ui/src/components/MarkedList/index.tsx, packages/ui/src/helpers/GridLines.tsx, packages/ui/src/index.ts, packages/ui/src/mixins/applyRoundness.ts, packages/ui/src/utils/animatedScrollTo.ts, packages/ui/src/utils/index.ts
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.112.7ad192ef7fa23b0b8b7d3cddd61b37a6744c8e2e.0
yarn add @sberdevices/ui@0.21.0-canary.112.7ad192ef7fa23b0b8b7d3cddd61b37a6744c8e2e.0
```
</details>
=> Доработка Header, Carousel, DeviceDetection и пр.

packages/ui/src/components/Carousel/Carousel.tsx, packages/ui/src/utils/setRef.ts, packages/ui/src/utils/useForkRef.ts
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.129.7ab9da7928236387147376e0d31622d331a5ea7b.0
yarn add @sberdevices/ui@0.21.0-canary.129.7ab9da7928236387147376e0d31622d331a5ea7b.0
```
</details>
=> feat(ui): проброс реф в компонент Carousel

packages/ui/src/components/Button/Button.tsx
<details>
<br />
```bash
npm install @sberdevices/ui@0.20.1-canary.132.e4605dc37264e70afc0073123ae052274d656d04.0
yarn add @sberdevices/ui@0.20.1-canary.132.e4605dc37264e70afc0073123ae052274d656d04.0
```
</details>
=> fix(ui): Типизация пропсов Button

packages/ui/.gitignore, packages/ui/package-lock.json, packages/ui/package.json, packages/ui/src/components/Carousel/Carousel.examples.tsx, packages/ui/src/components/Carousel/Carousel.hooks.tsx, packages/ui/src/components/Carousel/Carousel.mdx, packages/ui/src/components/Carousel/Carousel.stories.tsx, packages/ui/src/components/Carousel/Carousel.tsx, packages/ui/src/components/Carousel/Carousel.types.tsx, packages/ui/src/components/Carousel/CarouselCol.tsx, packages/ui/src/components/Carousel/CarouselContext.tsx, packages/ui/src/components/Carousel/CarouselItem.tsx, packages/ui/src/components/Carousel/CarouselWrapper.tsx, packages/ui/src/components/Carousel/index.ts, packages/ui/src/hooks/index.ts, packages/ui/src/hooks/useDebouncedFunction.ts, packages/ui/src/hooks/useForkRef.ts, packages/ui/src/index.ts
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.131.b0ca80ba63badf079ed48a5ebc203c20d1bf95f3.0
yarn add @sberdevices/ui@0.21.0-canary.131.b0ca80ba63badf079ed48a5ebc203c20d1bf95f3.0
```
</details>
=> feat(ui): Определение/Увеличение центрального элемента в Carousel

packages/ui/src/components/Header/Header.stories.tsx, packages/ui/src/components/Header/HeaderRoot.tsx
<details>
<br />
```bash
npm install @sberdevices/ui@0.20.1-canary.141.c5ab3a9547a018278a286cf9e2d52aba597bbebf.0
yarn add @sberdevices/ui@0.20.1-canary.141.c5ab3a9547a018278a286cf9e2d52aba597bbebf.0
```
</details>
=> fix(ui): Отображение HeaderButton отвязано от mediaQuery

packages/plasma-tokens/design-language/src/DesignLanguage.ts, packages/plasma-tokens/generate.ts, packages/ui/src/helpers/ColorsDemo.tsx
<details>
<br />
```bash
npm install demo-tokens@0.4.0-canary.138.a2e920370ecb7ab2498d3408ad32506826262335.0
npm install @sberdevices/plasma-icons@0.3.0-canary.138.a2e920370ecb7ab2498d3408ad32506826262335.0
npm install @sberdevices/plasma-tokens@0.5.0-canary.138.a2e920370ecb7ab2498d3408ad32506826262335.0
npm install @sberdevices/ui@0.21.0-canary.138.a2e920370ecb7ab2498d3408ad32506826262335.0
yarn add demo-tokens@0.4.0-canary.138.a2e920370ecb7ab2498d3408ad32506826262335.0
yarn add @sberdevices/plasma-icons@0.3.0-canary.138.a2e920370ecb7ab2498d3408ad32506826262335.0
yarn add @sberdevices/plasma-tokens@0.5.0-canary.138.a2e920370ecb7ab2498d3408ad32506826262335.0
yarn add …
```
=> feat(plasma-tokens): Градиенты подсказок о голосовых запросах

packages/ui/src/components/Button/ActionButton.tsx, packages/ui/src/components/Button/Button.mdx, packages/ui/src/components/Button/Button.stories.tsx, packages/ui/src/components/Button/Button.tsx, packages/ui/src/components/Card/Card.mdx, packages/ui/src/components/Card/Card.stories.tsx, packages/ui/src/components/Card/Card.tsx, packages/ui/src/components/Header/Header.stories.tsx, packages/ui/src/components/Skeleton/LineSkeleton.tsx, packages/ui/src/components/Skeleton/RectSkeleton.tsx, packages/ui/src/components/Skeleton/Skeleton.mdx, packages/ui/src/components/Skeleton/Skeleton.stories.tsx, packages/ui/src/components/Skeleton/TextSkeleton.tsx, packages/ui/src/components/Tabs/Tabs.mdx, packages/ui/src/components/Tabs/Tabs.stories.tsx, packages/ui/src/components/Tabs/Tabs.tsx, packages/ui/src/mixins/applyInteraction.ts, packages/ui/src/mixins/applyRoundness.ts, packages/ui/src/mixins/index.ts, packages/ui/src/mixins/mixins.mdx
closes #123 
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.140.8bf7f4a672ac6cb156db42f51303ea948508be94.0
yarn add @sberdevices/ui@0.21.0-canary.140.8bf7f4a672ac6cb156db42f51303ea948508be94.0
```
</details>
=> feat(ui): Доработаны миксины roundness/motion для карточки, кнопок и пр.

packages/ui/src/components/Button/ActionButton.tsx, packages/ui/src/components/Button/Button.stories.tsx, packages/ui/src/components/Button/Button.tsx, packages/ui/src/components/Card/Card.tsx, packages/ui/src/components/Header/HeaderBack.tsx, packages/ui/src/components/Tabs/Tabs.tsx, packages/ui/src/mixins/addFocus.ts, packages/ui/src/mixins/index.ts
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.153.ee4e5abd613d63a8e80bd80de5ecce493c3635ec.0
yarn add @sberdevices/ui@0.21.0-canary.153.ee4e5abd613d63a8e80bd80de5ecce493c3635ec.0
```
</details>
=> feat(ui): Тип FocusProps разложен на два подтипа

packages/ui/src/components/Checkbox/Basebox.tsx, packages/ui/src/components/Checkbox/Checkbox.mdx, packages/ui/src/components/Checkbox/Checkbox.stories.tsx, packages/ui/src/components/Checkbox/Checkbox.tsx, packages/ui/src/components/Checkbox/index.ts, packages/ui/src/components/Radiobox/Radiobox.mdx, packages/ui/src/components/Radiobox/Radiobox.stories.tsx, packages/ui/src/components/Radiobox/Radiobox.tsx, packages/ui/src/components/Radiobox/RadioboxList.tsx, packages/ui/src/components/Radiobox/index.ts, packages/ui/src/types/InputHTMLAttributes.ts, packages/ui/src/types/index.ts
Closes #149, #150 
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.162.8045aa4615bb528382dc5356455fa90790371ce1.0
yarn add @sberdevices/ui@0.21.0-canary.162.8045aa4615bb528382dc5356455fa90790371ce1.0
```
</details>
=> feat(ui): Компоненты Checkbox & Radiobox

packages/ui/src/components/Card/Card.examples.tsx, packages/ui/src/components/Carousel/Carousel.stories.tsx, packages/ui/src/components/Carousel/Carousel.tsx
Closes #163 
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.175.31c653c5c58dccdd0b2406af8797d3ce2a3a5196.0
yarn add @sberdevices/ui@0.21.0-canary.175.31c653c5c58dccdd0b2406af8797d3ce2a3a5196.0
```
</details>
=> feat(ui): Добавлен пример с вертикальной каруселью

packages/ui/src/components/Carousel/Carousel.tsx
<details>
<br />
```bash
npm install @sberdevices/ui@0.20.1-canary.183.49fe4e21a70ac5b5cee09e36252d17203bbba36a.0
yarn add @sberdevices/ui@0.20.1-canary.183.49fe4e21a70ac5b5cee09e36252d17203bbba36a.0
```
</details>
=> fix(ui): Исправлена невозможность передать -1 index в Carousel, #182

packages/ui/src/components/Pickers/DatePicker.tsx, packages/ui/src/components/Pickers/Picker.tsx, packages/ui/src/components/Pickers/PickerItem.tsx, packages/ui/src/components/Pickers/Pickers.mdx, packages/ui/src/components/Pickers/Pickers.stories.tsx, packages/ui/src/components/Pickers/SimpleDatePicker.tsx, packages/ui/src/components/Pickers/SimpleTimePicker.tsx, packages/ui/src/components/Pickers/TimePicker.tsx, packages/ui/src/components/Pickers/index.ts, packages/ui/src/index.ts, packages/ui/src/utils/formatters.ts
Closes #101 
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.114.67a917ec47026a10b38b0949abd59cb753ffdfc7.0
yarn add @sberdevices/ui@0.21.0-canary.114.67a917ec47026a10b38b0949abd59cb753ffdfc7.0
```
</details>
=> feat(ui): Компоненты DatePicker & TimePicker

packages/ui/src/components/Carousel/Carousel.stories.tsx, packages/ui/src/components/Carousel/Carousel.tsx, packages/ui/src/components/Carousel/CarouselGridWrapper.tsx, packages/ui/src/components/Pickers/Picker.tsx
<details>
<br />
```bash
npm install @sberdevices/ui@1.0.0-canary.187.aa38e700390b4bcfbfb890bcb733d80ff24c422c.0
yarn add @sberdevices/ui@1.0.0-canary.187.aa38e700390b4bcfbfb890bcb733d80ff24c422c.0
```
</details>
=> feat(ui): Добавлен параметр scrollAlign для карусели

packages/ui/src/components/Stepper/Stepper.tsx
<details>
<br />
```bash
npm install @sberdevices/ui@0.20.1-canary.197.37d2445708eaf5f64438fb99960ada63fd858d2b.0
yarn add @sberdevices/ui@0.20.1-canary.197.37d2445708eaf5f64438fb99960ada63fd858d2b.0
```
</details>
=> fix(ui): Поправлены импорты степпера

packages/ui/src/utils/deviceDetection.ts
<details>
<br />
```bash
npm install @sberdevices/ui@0.20.1-canary.194.e745d0bc6786cafe677d9f47a0970577d7096c1a.0
yarn add @sberdevices/ui@0.20.1-canary.194.e745d0bc6786cafe677d9f47a0970577d7096c1a.0
```
</details>
=> fix(ui): detection of portal

packages/ui/src/components/Switch/Switch.stories.tsx, packages/ui/src/components/Switch/Switch.tsx, packages/ui/src/components/Switch/index.ts, packages/ui/src/index.ts, packages/ui/src/mixins/addFocus.ts
Closes #151 
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.188.648e1174399780c951097ed7f9adc96e98dd8e0a.0
yarn add @sberdevices/ui@0.21.0-canary.188.648e1174399780c951097ed7f9adc96e98dd8e0a.0
```
</details>
=> feat(ui): Компонент Switch

packages/ui/src/components/Button/ActionButton.tsx
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.192.6ae02b44c0860788b454457209ca862b06d710b5.0
yarn add @sberdevices/ui@0.21.0-canary.192.6ae02b44c0860788b454457209ca862b06d710b5.0
```
</details>
=> feat(ui): ActionButton ref

packages/ui/src/components/PaginationDots/PaginationDot.tsx, packages/ui/src/components/PaginationDots/PaginationDots.stories.mdx, packages/ui/src/components/PaginationDots/PaginationDots.stories.tsx, packages/ui/src/components/PaginationDots/PaginationDots.tsx, packages/ui/src/components/PaginationDots/SmartPaginationDots.tsx, packages/ui/src/components/PaginationDots/index.ts, packages/ui/src/index.ts
Closes #152 
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.190.5cbfcf3da6551a603b8e943913e8890bf059994f.0
yarn add @sberdevices/ui@0.21.0-canary.190.5cbfcf3da6551a603b8e943913e8890bf059994f.0
```
</details>
=> feat(ui): Компонент PaginationDots

packages/ui/src/components/Button/Button.stories.tsx, packages/ui/src/components/Button/Button.tsx, packages/ui/src/components/Carousel/Carousel.examples.tsx, packages/ui/src/components/Carousel/Carousel.hooks.tsx, packages/ui/src/components/Carousel/Carousel.mdx, packages/ui/src/components/Carousel/Carousel.stories.tsx, packages/ui/src/components/Carousel/Carousel.tsx, packages/ui/src/components/Header/Header.stories.tsx, packages/ui/src/components/Header/Header.tsx, packages/ui/src/components/Header/HeaderBack.tsx, packages/ui/src/components/Header/HeaderButton.tsx, packages/ui/src/components/Pickers/Picker.tsx, packages/ui/src/components/Stepper/Stepper.stories.tsx, packages/ui/src/components/Stepper/Stepper.tsx, packages/ui/src/components/TextField/TextField.stories.tsx, packages/ui/src/components/TextField/TextField.tsx
closes #164 
<details>
<br />
```bash
npm install @sberdevices/ui@1.0.0-canary.174.72bdc6abd26565e3c512df142df429921ee4fb54.0
yarn add @sberdevices/ui@1.0.0-canary.174.72bdc6abd26565e3c512df142df429921ee4fb54.0
```
</details>
=> Приведены типы пропсов в порядок

packages/ui/src/components/Badge/Badge.stories.tsx, packages/ui/src/components/Button/Button.stories.tsx, packages/ui/src/components/Card/Card.examples.tsx, packages/ui/src/components/Card/Card.tsx, packages/ui/src/components/Checkbox/Basebox.tsx, packages/ui/src/components/Checkbox/Checkbox.stories.tsx, packages/ui/src/components/MarkedList/MarkedList.stories.tsx, packages/ui/src/components/Stepper/Stepper.tsx, packages/ui/src/components/Tabs/TabItem.tsx, packages/ui/src/components/TextField/TextField.tsx, packages/ui/src/components/Toast/Toast.tsx
<details>
<br />
```bash
npm install @sberdevices/ui@0.20.1-canary.209.9778314df39bbc3f2905b2eb98e745e79c61ef2d.0
yarn add @sberdevices/ui@0.20.1-canary.209.9778314df39bbc3f2905b2eb98e745e79c61ef2d.0
```
</details>
=> fix(ui): Исправлены недоработки компонентов в светлой теме

packages/ui/src/components/Card/CardPrice.tsx, packages/ui/src/components/Price/Price.stories.tsx, packages/ui/src/components/Price/Price.tsx, packages/ui/src/components/Price/index.ts, packages/ui/src/helpers/formatCurrency.ts, packages/ui/src/index.ts, packages/ui/src/utils/formatCurrency.ts, packages/ui/src/utils/index.ts
Closes #81 
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.210.6cfde4a762b3405ea58642b47bc7f7067376108d.0
yarn add @sberdevices/ui@0.21.0-canary.210.6cfde4a762b3405ea58642b47bc7f7067376108d.0
```
</details>
=> feat(ui): Компонент Price

packages/ui/src/components/Button/Button.stories.mdx, packages/ui/src/components/Carousel/Carousel.tsx, packages/ui/src/components/Carousel/CarouselGridWrapper.tsx, packages/ui/src/components/Cell/Cell.stories.tsx, packages/ui/src/components/Cell/Cell.tsx, packages/ui/src/components/Cell/CellDisclosure.tsx, packages/ui/src/components/Fade/Fade.tsx, packages/ui/src/components/Fade/index.ts, packages/ui/src/components/Header/Header.stories.mdx, packages/ui/src/components/Header/Header.stories.tsx, packages/ui/src/components/MarkedList/MarkedList.tsx, packages/ui/src/components/Tabs/TabItem.tsx, packages/ui/src/components/Tabs/Tabs.stories.tsx, packages/ui/src/components/Tabs/Tabs.tsx, packages/ui/src/components/TextField/TextField.stories.tsx, packages/ui/src/components/TextField/TextField.tsx, packages/ui/src/components/Toast/Toast.stories.tsx, packages/ui/src/components/Toast/ToastController.tsx, packages/ui/src/components/Toast/ToastProvider.tsx, packages/ui/src/components/Toast/types.ts, packages/ui/src/mixins/addFocus.ts, packages/ui/src/mixins/applyInteraction.ts
* fix(ui): Tabs сдвиг для outline, rem-ы, убран scaleOnHover
* fix(ui): TextField пример с content, rem-ы, cursor
* docs(ui): Button дополнен раздел документации о круглых кнопках
* feat(ui): Cell кликабельная область с Disclosure, outline
* feat(ui): Toast добавлена анимация появления / исчезания
* feat(ui): Компонент Fade, Toast + Fade
* docs(ui): Header доработаны примеры в stories
* fix(ui): MarkedList отступ 12px
* fix(ui): Carousel исправление overscroll-отступов
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.212.38f24ed29d0315dc9ee8cc09269d92adda5a4ce1.0
yarn add @sberdevices/ui@0.21.0-canary.212.38f24ed29d0315dc9ee8cc09269d92adda5a4ce1.0 …
```
=> Доработки компонентов

packages/ui/src/components/Card/Card.stories.tsx, packages/ui/src/components/Card/CardMedia.tsx, packages/ui/src/components/Carousel/Carousel.examples.tsx, packages/ui/src/components/Carousel/Carousel.stories.tsx, packages/ui/src/components/Image/Image.stories.tsx, packages/ui/src/components/Image/Image.tsx, packages/ui/src/components/Image/index.ts
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.189.3d1ae4868c0cbfce53a472710a455d1c5d806f0c.0
yarn add @sberdevices/ui@0.21.0-canary.189.3d1ae4868c0cbfce53a472710a455d1c5d806f0c.0
```
</details>
=> Компонент Image, CardMedia placeholder

packages/ui/src/utils/deviceDetection.ts
Closes #202 
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.211.fc47e7ba557ea34cd0e525f06db777a604f784be.0
yarn add @sberdevices/ui@0.21.0-canary.211.fc47e7ba557ea34cd0e525f06db777a604f784be.0
```
</details>
=> feat(ui): Определение TV

packages/ui/src/components/Spinner/Spinner.tsx, packages/ui/src/components/Spinner/WhiteSpinnerSvg.tsx
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.230.ca5eee2f4fb09e7fdfd2c62112cc0e6f4649896d.0
yarn add @sberdevices/ui@0.21.0-canary.230.ca5eee2f4fb09e7fdfd2c62112cc0e6f4649896d.0
```
</details>
=> fix: Add white Spinner

packages/ui/src/components/Stepper/StepperButton.tsx
https://github.com/sberdevices/plasma/issues/232
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.237.ae44759ecde382cf13d5de334eeed2aa9258df18.0
yarn add @sberdevices/ui@0.21.0-canary.237.ae44759ecde382cf13d5de334eeed2aa9258df18.0
```
</details>
=> feat: добавил поддержку ref для кнопок у Stepper

packages/plasma-core/src/components/Button/Button.stories.tsx, packages/plasma-core/src/components/Button/Button.tsx, packages/plasma-core/src/components/Button/Button.types.ts, packages/plasma-core/src/mixins/applyView.ts, packages/plasma-core/src/mixins/blur.ts, packages/plasma-core/src/mixins/index.ts, packages/plasma-icons/src/IconRoot.tsx, packages/ui/src/components/Button/Button.examples.tsx, packages/ui/src/components/Button/Button.stories.tsx, packages/ui/src/mixins/mixins.stories.mdx, packages/ui/src/mixins/mixins.stories.tsx
<details>
<br />
```bash
npm install @sberdevices/plasma-core@2.0.0-canary.240.e10e5f53feedb2dfe36cdc1fd3373dffdeb10ab0.0
npm install @sberdevices/plasma-icons@1.0.0-canary.240.e10e5f53feedb2dfe36cdc1fd3373dffdeb10ab0.0
npm install @sberdevices/plasma-web@2.0.0-canary.240.e10e5f53feedb2dfe36cdc1fd3373dffdeb10ab0.0
npm install @sberdevices/ui@1.0.0-canary.240.e10e5f53feedb2dfe36cdc1fd3373dffdeb10ab0.0
yarn add @sberdevices/plasma-core@2.0.0-canary.240.e10e5f53feedb2dfe36cdc1fd3373dffdeb10ab0.0
yarn add @sberdevices/plasma-icons@1.0.0-canary.240.e10e5f53feedb2dfe36cdc1fd3373dffdeb10ab0.0
yarn add @sberdevices/plasma-web@2.0.0-canary.240.e10e5f53feedb2dfe36cdc1fd3373dffde …
```
=> Доработки кнопок, документация для миксинов

packages/ui/package-lock.json, packages/ui/src/components/Card/Card.stories.mdx, packages/ui/src/components/Card/CardMedia.tsx, packages/ui/src/components/Image/Image.tsx, packages/ui/src/components/Image/index.ts
<details>
<br />
```bash
npm install @sberdevices/ui@0.20.1-canary.239.045b1fd64ad41d0a80a757354e150392f61fc2a7.0
yarn add @sberdevices/ui@0.20.1-canary.239.045b1fd64ad41d0a80a757354e150392f61fc2a7.0
```
</details>
=> fix(plasma-ui): CardMedia has children

packages/ui/src/components/RunningString/RunningString.stories.tsx, packages/ui/src/components/RunningString/RunningString.tsx, packages/ui/src/components/RunningString/index.ts
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.256.fb38a7df70462f5e16fe499af5c8bde3b2c89342.0
yarn add @sberdevices/ui@0.21.0-canary.256.fb38a7df70462f5e16fe499af5c8bde3b2c89342.0
```
</details>
=> feat(ui): Добавлена бегущая строка

packages/ui/src/components/Marquee/Marquee.tsx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.1.1-canary.261.5a6b4fb5fe498fb434a15fcb22905c86dc20ab58.0
npm install @sberdevices/ui@0.20.1-canary.261.5a6b4fb5fe498fb434a15fcb22905c86dc20ab58.0
yarn add @sberdevices/showcase@0.1.1-canary.261.5a6b4fb5fe498fb434a15fcb22905c86dc20ab58.0
yarn add @sberdevices/ui@0.20.1-canary.261.5a6b4fb5fe498fb434a15fcb22905c86dc20ab58.0
```
</details>
=> fix(ui): Фикс компонента бегущей строки

docs/showcase/.storybook/preview.js, docs/showcase/src/helpers/StoryDecorators.tsx, docs/showcase/src/ui/Header.stories.tsx, packages/plasma-core/src/components/Basebox/Basebox.tsx, packages/plasma-core/src/components/Button/Button.tsx, packages/plasma-core/src/components/Switch/Switch.tsx, packages/plasma-core/src/components/Tabs/Tabs.tsx, packages/ui/src/components/Header/Header.stories.mdx, packages/ui/src/components/Header/Header.stories.tsx, packages/ui/src/components/Header/Header.tsx, packages/ui/src/components/Header/HeaderBack.tsx, packages/ui/src/components/Header/HeaderButton.tsx, packages/ui/src/components/Header/HeaderContent.tsx, packages/ui/src/components/Header/HeaderLogo.tsx, packages/ui/src/components/Header/HeaderRoot.tsx, packages/ui/src/components/Header/HeaderSubtitle.tsx, packages/ui/src/components/Header/HeaderTitle.tsx, packages/ui/src/components/Header/HeaderTitleWrapper.tsx, packages/ui/src/components/Tabs/Tabs.tsx
fix(ui): Header: layout, height, text shortening, logo (#254)
fix(ui): Header: pair props in interface (#233)
fix(plasma-core): removed highlight on component tap in Chrome (#262)
fix(ui): Tabs: fixed border-radius when `pilled=true`
<details>
<br />
```bash
npm install @sberdevices/showcase@0.1.1-canary.265.68a51d622e0974d0cdb3c0f524f4e5662239d386.0
npm install @sberdevices/plasma-core@0.5.1-canary.265.68a51d622e0974d0cdb3c0f524f4e5662239d386.0
npm install @sberdevices/plasma-web@0.2.1-canary.265.68a51d622e0974d0cdb3c0f524f4e5662239d386.0
npm install @sberdevices/ui@0.20.1-canary.265.68a51d622e0974d0cdb3c0f524f4e5662239d386.0
yarn add …
```
=> List of fixes

.github/workflows/release.yml, package.json, packages/plasma-ui/src/components/Marquee/Marquee.tsx
and ci fixes for protected branch
<details>
<br />
```bash
npm install @sberdevices/showcase@0.2.0-canary.284.a163cacf340440188d48cd6a970c21815424a13a.0
npm install demo-tokens@0.4.0-canary.284.a163cacf340440188d48cd6a970c21815424a13a.0
npm install @sberdevices/plasma-core@1.1.0-canary.284.a163cacf340440188d48cd6a970c21815424a13a.0
npm install @sberdevices/plasma-icons@1.1.0-canary.284.a163cacf340440188d48cd6a970c21815424a13a.0
npm install @sberdevices/plasma-tokens-android@2.1.0-canary.284.a163cacf340440188d48cd6a970c21815424a13a.0
npm install @sberdevices/plasma-tokens-ios-swift@2.1.0-canary.284.a163cacf340440188d48cd6a970c21815424a13a.0
npm install …
```
=> Marquee: animation duration prop

.github/workflows/documentation-pr.yml, .github/workflows/release.yml
<details>
<br />
```bash
npm install @sberdevices/showcase@0.1.1-canary.285.6fee0eff6573053d5401b7832d09982d37446977.0
npm install demo-tokens@0.3.1-canary.285.6fee0eff6573053d5401b7832d09982d37446977.0
npm install @sberdevices/plasma-core@1.0.1-canary.285.6fee0eff6573053d5401b7832d09982d37446977.0
npm install @sberdevices/plasma-icons@1.0.1-canary.285.6fee0eff6573053d5401b7832d09982d37446977.0
npm install @sberdevices/plasma-tokens-android@2.0.1-canary.285.6fee0eff6573053d5401b7832d09982d37446977.0
npm install @sberdevices/plasma-tokens-ios-swift@2.0.1-canary.285.6fee0eff6573053d5401b7832d09982d37446977.0
npm install …
```
=> fix: release

docs/showcase/src/web/TextArea.stories.tsx, packages/plasma-web/src/components/TextArea/TextArea.stories.tsx, packages/plasma-web/src/components/TextArea/TextArea.tsx, packages/plasma-web/src/components/TextArea/index.ts, packages/plasma-web/src/components/TextField/TextField.tsx, packages/plasma-web/src/index.ts
<details>
<br />
```bash
npm install @sberdevices/showcase@0.7.0-canary.290.59f327f8a2129d6e411a3440653306e9b8fdc7cb.0
npm install @sberdevices/plasma-web@1.2.0-canary.290.59f327f8a2129d6e411a3440653306e9b8fdc7cb.0
yarn add @sberdevices/showcase@0.7.0-canary.290.59f327f8a2129d6e411a3440653306e9b8fdc7cb.0
yarn add @sberdevices/plasma-web@1.2.0-canary.290.59f327f8a2129d6e411a3440653306e9b8fdc7cb.0
```
</details>
=> feat(plasma-web): Added TextArea component

packages/plasma-ui/src/utils/deviceDetection.ts
<details>
<br />
```bash
npm install @sberdevices/showcase@0.9.1-canary.312.6208e18e3d0e2147cfdb891da53aafb676ca6f96.0
npm install @sberdevices/plasma-ui@1.5.1-canary.312.6208e18e3d0e2147cfdb891da53aafb676ca6f96.0
yarn add @sberdevices/showcase@0.9.1-canary.312.6208e18e3d0e2147cfdb891da53aafb676ca6f96.0
yarn add @sberdevices/plasma-ui@1.5.1-canary.312.6208e18e3d0e2147cfdb891da53aafb676ca6f96.0
```
</details>
=> fix(plasma-ui): fix detection Huawei TV

docs/showcase/package-lock.json, docs/showcase/package.json, docs/showcase/src/ui/Pickers.stories.tsx, packages/plasma-ui/src/components/Carousel/Carousel.hooks.tsx, packages/plasma-ui/src/components/Pickers/DatePicker.tsx, packages/plasma-ui/src/components/Pickers/Picker.tsx, packages/plasma-ui/src/components/Pickers/PickerItem.tsx, packages/plasma-ui/src/components/Pickers/Pickers.stories.tsx, packages/plasma-ui/src/components/Pickers/SimpleDatePicker.tsx, packages/plasma-ui/src/components/Pickers/SimpleTimePicker.tsx, packages/plasma-ui/src/components/Pickers/TimePicker.tsx
<details>
<br />
```bash
npm install @sberdevices/plasma-ui@1.6.0-canary.300.02148409f793ec7592160521c1439416e189b460.0
yarn add @sberdevices/plasma-ui@1.6.0-canary.300.02148409f793ec7592160521c1439416e189b460.0
```
</details>
=> Date/TimePickers: enhancements & bugfixes

packages/plasma-ui/src/components/Pickers/DatePicker.tsx, packages/plasma-ui/src/components/Pickers/Pickers.stories.tsx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.10.2-canary.322.ff655b4feede0a8683268e348fa3362a3b07cff8.0
npm install @sberdevices/plasma-ui@1.6.2-canary.322.ff655b4feede0a8683268e348fa3362a3b07cff8.0
yarn add @sberdevices/showcase@0.10.2-canary.322.ff655b4feede0a8683268e348fa3362a3b07cff8.0
yarn add @sberdevices/plasma-ui@1.6.2-canary.322.ff655b4feede0a8683268e348fa3362a3b07cff8.0
```
</details>
=> fix(plasma-ui): DatePicker: fix 30-31 february

docs/showcase/src/helpers/TextFieldShowcase.tsx, docs/showcase/src/web/Select.stories.tsx, packages/plasma-core/src/components/TextField/TextField.tsx, packages/plasma-web/src/components/Select/MultiSelect.tsx, packages/plasma-web/src/components/Select/Select.stories.tsx, packages/plasma-web/src/components/Select/Select.tsx, packages/plasma-web/src/components/Select/SelectDropdown.tsx, packages/plasma-web/src/components/Select/SelectList.tsx, packages/plasma-web/src/components/Select/SelectView.tsx, packages/plasma-web/src/components/Select/SingleSelect.tsx, packages/plasma-web/src/components/Select/index.ts
<details>
<br />
```bash
npm install @sberdevices/showcase@0.11.0-canary.328.65a18d98d0bfd4b12062519df244b3c42c48abb3.0
npm install @sberdevices/plasma-core@1.5.0-canary.328.65a18d98d0bfd4b12062519df244b3c42c48abb3.0
npm install @sberdevices/plasma-icons@1.5.0-canary.328.65a18d98d0bfd4b12062519df244b3c42c48abb3.0
npm install @sberdevices/plasma-ui@1.7.0-canary.328.65a18d98d0bfd4b12062519df244b3c42c48abb3.0
npm install @sberdevices/plasma-web@1.6.0-canary.328.65a18d98d0bfd4b12062519df244b3c42c48abb3.0
yarn add @sberdevices/showcase@0.11.0-canary.328.65a18d98d0bfd4b12062519df244b3c42c48abb3.0
yarn add @sberdevices/plasma-core@1.5.0-canary.328.65a18d98d0bfd4b12062519df244 …
```
=> feat(plasma-web): Added Select component

.github/workflows/release.yml
Исправление сообщения коммита и авторства коммита
=> Update package locks

docs/showcase/src/helpers/BadgeShowcase.tsx, docs/showcase/src/web/Progress.stories.tsx, packages/plasma-web/src/components/Progress/Progress.stories.tsx, packages/plasma-web/src/components/Progress/Progress.tsx, packages/plasma-web/src/components/Progress/index.ts, packages/plasma-web/src/index.ts
<details>
<br />
```bash
npm install @sberdevices/showcase@0.14.0-canary.340.6a4f5f1479188533ed161f58e0b59ad6323527e5.0
npm install @sberdevices/plasma-icons@1.7.0-canary.340.6a4f5f1479188533ed161f58e0b59ad6323527e5.0
npm install @sberdevices/plasma-tokens-web@1.3.0-canary.340.6a4f5f1479188533ed161f58e0b59ad6323527e5.0
npm install @sberdevices/plasma-tokens@1.3.0-canary.340.6a4f5f1479188533ed161f58e0b59ad6323527e5.0
npm install @sberdevices/plasma-ui@1.10.0-canary.340.6a4f5f1479188533ed161f58e0b59ad6323527e5.0
npm install @sberdevices/plasma-web@1.8.0-canary.340.6a4f5f1479188533ed161f58e0b59ad6323527e5.0
npm install …
```
=> feat(plasma-web): Added Progress component

packages/plasma-core/src/components/Button/Button.tsx, packages/plasma-core/src/components/Switch/Switch.tsx, packages/plasma-core/src/components/Tabs/Tabs.tsx, packages/plasma-core/src/components/TextField/TextField.tsx, packages/plasma-core/src/mixins/applyEllipsis.ts, packages/plasma-core/src/mixins/index.ts, packages/plasma-ui/src/mixins/mixins.stories.mdx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.14.0-canary.348.21d16ef749db95645c6e854c4cab16b1f0b3a6b3.0
npm install @sberdevices/plasma-core@1.7.0-canary.348.21d16ef749db95645c6e854c4cab16b1f0b3a6b3.0
npm install @sberdevices/plasma-icons@1.7.0-canary.348.21d16ef749db95645c6e854c4cab16b1f0b3a6b3.0
npm install @sberdevices/plasma-tokens-web@1.3.0-canary.348.21d16ef749db95645c6e854c4cab16b1f0b3a6b3.0
npm install @sberdevices/plasma-tokens@1.3.0-canary.348.21d16ef749db95645c6e854c4cab16b1f0b3a6b3.0
npm install @sberdevices/plasma-ui@1.10.0-canary.348.21d16ef749db95645c6e854c4cab16b1f0b3a6b3.0
npm install …
```
=> feat(plasma-core): Added applyEllipsis mixin

docs/showcase/src/web/Tooltip.stories.tsx, packages/plasma-web/package-lock.json, packages/plasma-web/package.json, packages/plasma-web/src/components/Tooltip/Tooltip.stories.mdx, packages/plasma-web/src/components/Tooltip/Tooltip.stories.tsx, packages/plasma-web/src/components/Tooltip/Tooltip.tsx, packages/plasma-web/src/components/Tooltip/index.ts, packages/plasma-web/src/index.ts
Took commit from https://github.com/sberdevices/plasma/pull/339
<details>
<br />
```bash
npm install @sberdevices/showcase@0.17.0-canary.345.b791016d8f2a7dddb0f899b48089fc3d5cd65b60.0
npm install @sberdevices/plasma-icons@1.10.0-canary.345.b791016d8f2a7dddb0f899b48089fc3d5cd65b60.0
npm install @sberdevices/plasma-ui@1.13.0-canary.345.b791016d8f2a7dddb0f899b48089fc3d5cd65b60.0
npm install @sberdevices/plasma-web@1.11.0-canary.345.b791016d8f2a7dddb0f899b48089fc3d5cd65b60.0
yarn add @sberdevices/showcase@0.17.0-canary.345.b791016d8f2a7dddb0f899b48089fc3d5cd65b60.0
yarn add @sberdevices/plasma-icons@1.10.0-canary.345.b791016d8f2a7dddb0f899b48089fc3d5cd65b60.0
yarn add …
```
=> feat(plasma-web): Added Tooltip component

packages/plasma-web/src/index.ts
<details>
<br />
```bash
npm install @sberdevices/showcase@0.18.2-canary.397.dcf495d72910c1f765e27a86bf249396b1038ca2.0
npm install @sberdevices/plasma-ui@1.14.2-canary.397.dcf495d72910c1f765e27a86bf249396b1038ca2.0
npm install @sberdevices/plasma-web@1.12.2-canary.397.dcf495d72910c1f765e27a86bf249396b1038ca2.0
yarn add @sberdevices/showcase@0.18.2-canary.397.dcf495d72910c1f765e27a86bf249396b1038ca2.0
yarn add @sberdevices/plasma-ui@1.14.2-canary.397.dcf495d72910c1f765e27a86bf249396b1038ca2.0
yarn add @sberdevices/plasma-web@1.12.2-canary.397.dcf495d72910c1f765e27a86bf249396b1038ca2.0
```
</details>
=> fix(plasma-web): Added Badge to index

packages/plasma-ui/src/utils/deviceDetection.ts
<details>
<br />
```bash
npm install @sberdevices/showcase@0.19.1-canary.403.3e29f29a1fb2610546f622584becc78d3b3bde11.0
npm install @sberdevices/plasma-icons@1.12.1-canary.403.3e29f29a1fb2610546f622584becc78d3b3bde11.0
npm install @sberdevices/plasma-ui@1.15.1-canary.403.3e29f29a1fb2610546f622584becc78d3b3bde11.0
npm install @sberdevices/plasma-web@1.13.1-canary.403.3e29f29a1fb2610546f622584becc78d3b3bde11.0
yarn add @sberdevices/showcase@0.19.1-canary.403.3e29f29a1fb2610546f622584becc78d3b3bde11.0
yarn add @sberdevices/plasma-icons@1.12.1-canary.403.3e29f29a1fb2610546f622584becc78d3b3bde11.0
yarn add @sberdevices/plasma-ui@1.15.1-canary.403.3e29f29a1fb2610546f622584be …
```
=> fix(plasma-ui) Add Huawei TV UA

packages/plasma-core/README.md
<details>
<br />
```bash
npm install @sberdevices/showcase@0.22.0-canary.432.4f4e6411f0fbc179e4415a836ff51476c5e5feb7.0
npm install @sberdevices/plasma-core@1.12.0-canary.432.4f4e6411f0fbc179e4415a836ff51476c5e5feb7.0
npm install @sberdevices/plasma-icons@1.15.0-canary.432.4f4e6411f0fbc179e4415a836ff51476c5e5feb7.0
npm install @sberdevices/plasma-ui@1.18.0-canary.432.4f4e6411f0fbc179e4415a836ff51476c5e5feb7.0
npm install @sberdevices/plasma-web@1.16.0-canary.432.4f4e6411f0fbc179e4415a836ff51476c5e5feb7.0
npm install @sberdevices/plasma-tokens-android@2.7.0-canary.432.4f4e6411f0fbc179e4415a836ff51476c5e5feb7.0
npm install …
```
=> feat: bump plasma-core

packages/plasma-ui/README.md, packages/plasma-web/.storybook/main.js, packages/plasma-web/.storybook/preview.js, packages/plasma-web/README.stories.mdx
fixes: https://github.com/sberdevices/plasma/issues/427
=> docs(plasma-ui): repository link added

packages/plasma-core/.babelrc, packages/plasma-core/package-lock.json, packages/plasma-core/package.json, packages/plasma-core/rollup.config.js, packages/plasma-core/src/components/Checkbox/Checkbox.tsx, packages/plasma-core/src/components/TextField/TextField.tsx, packages/plasma-core/src/types/InputHTMLAttributes.ts, packages/plasma-core/src/types/TextareaHTMLAttributes.ts, packages/plasma-ui/rollup.config.js, packages/plasma-ui/src/components/Checkbox/Checkbox.tsx, packages/plasma-ui/src/components/Radiobox/Radiobox.tsx, packages/plasma-ui/src/components/TextArea/TextArea.tsx, packages/plasma-ui/src/components/TextField/TextField.tsx, packages/plasma-web/rollup.config.js, packages/plasma-web/src/components/Checkbox/Checkbox.tsx, packages/plasma-web/src/components/Field/Field.tsx, packages/plasma-web/src/components/Radiobox/Radiobox.tsx, packages/plasma-web/src/components/Select/SelectView.tsx, packages/plasma-web/src/components/TextArea/TextArea.tsx, packages/plasma-web/src/components/TextField/TextField.stories.tsx, packages/plasma-web/src/components/TextField/TextField.tsx, rollup.config.js
- Added htmlFor attribute for checkbox's label
- Refactored input's interface
<details>
<br />
```bash
npm install @sberdevices/showcase@0.28.0-canary.463.9a78da8ac38b059aa7393d0e0a08028c5305e2a9.0
npm install @sberdevices/plasma-core@1.16.0-canary.463.9a78da8ac38b059aa7393d0e0a08028c5305e2a9.0
npm install @sberdevices/plasma-icons@1.21.0-canary.463.9a78da8ac38b059aa7393d0e0a08028c5305e2a9.0
npm install @sberdevices/plasma-ui@1.24.0-canary.463.9a78da8ac38b059aa7393d0e0a08028c5305e2a9.0
npm install @sberdevices/plasma-web@1.22.0-canary.463.9a78da8ac38b059aa7393d0e0a08028c5305e2a9.0
npm install @sberdevices/plasma-sb-utils@0.6.0-canary.463.9a78da8ac38b059aa7393d0e0a08028 …
```
=> fix: Checkbox & Input fixes

.github/workflows/clean-pr-documentation.yml, .github/workflows/examples-pr.yml, .github/workflows/examples.yml, examples/demo-canvas-app/.babelrc, examples/demo-canvas-app/.env.production, examples/demo-canvas-app/.gitignore, examples/demo-canvas-app/README.md, examples/demo-canvas-app/components/GlobalStyle.tsx, examples/demo-canvas-app/components/index.ts, examples/demo-canvas-app/next-env.d.ts, examples/demo-canvas-app/next.config.js, examples/demo-canvas-app/package-lock.json, examples/demo-canvas-app/package.json, examples/demo-canvas-app/pages/_app.tsx, examples/demo-canvas-app/pages/_document.tsx, examples/demo-canvas-app/pages/index.tsx, examples/demo-canvas-app/pages/test/components/pickers.tsx, examples/demo-canvas-app/pages/test/components/switch.tsx, examples/demo-canvas-app/pages/test/components/text-field.tsx, examples/demo-canvas-app/tsconfig.json, packages/plasma-core/src/components/Switch/Switch.tsx, packages/plasma-ui/src/components/Pickers/DatePicker.tsx, packages/plasma-ui/src/components/Pickers/Picker.tsx, packages/plasma-ui/src/components/Pickers/SimpleDatePicker.tsx, packages/plasma-ui/src/components/Pickers/SimpleTimePicker.tsx, packages/plasma-ui/src/components/Pickers/TimePicker.tsx, packages/plasma-ui/src/hocs/hocs.stories.mdx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.30.0-canary.494.c51dd91226eecc1bad8fc54f73bf8be59c5f71c7.0
npm install @sberdevices/demo-canvas-app@0.2.0-canary.494.c51dd91226eecc1bad8fc54f73bf8be59c5f71c7.0
npm install @sberdevices/plasma-core@1.17.0-canary.494.c51dd91226eecc1bad8fc54f73bf8be59c5f71c7.0
npm install @sberdevices/plasma-icons@1.22.0-canary.494.c51dd91226eecc1bad8fc54f73bf8be59c5f71c7.0
npm install @sberdevices/plasma-ui@1.26.0-canary.494.c51dd91226eecc1bad8fc54f73bf8be59c5f71c7.0
npm install @sberdevices/plasma-web@1.24.0-canary.494.c51dd91226eecc1bad8fc54f73bf8be59c5f71c7.0
npm install …
```
=> fix focus & demo canvas app

packages/plasma-ui/src/components/Header/HeaderBack.tsx, packages/plasma-ui/src/components/Header/HeaderRoot.tsx
https://github.com/sberdevices/plasma/pull/503
<details>
<br />
```bash
npm install @sberdevices/showcase@0.29.1-canary.517.6362184244249881b20907da6ea9cbf88f3bbd65.0
npm install @sberdevices/demo-canvas-app@0.1.1-canary.517.6362184244249881b20907da6ea9cbf88f3bbd65.0
npm install @sberdevices/plasma-core@1.16.1-canary.517.6362184244249881b20907da6ea9cbf88f3bbd65.0
npm install @sberdevices/plasma-icons@1.21.2-canary.517.6362184244249881b20907da6ea9cbf88f3bbd65.0
npm install @sberdevices/plasma-ui@1.25.1-canary.517.6362184244249881b20907da6ea9cbf88f3bbd65.0
npm install @sberdevices/plasma-web@1.23.1-canary.517.6362184244249881b20907da6ea9cbf88f3bbd65.0
npm install …
```
=> fix(plasma-ui): Header back button position

examples/demo-canvas-app/pages/test/components/pickers.tsx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.33.0-canary.542.e86662d3c5ab7e114b7f4756ae56e4dec468ee24.0
npm install @sberdevices/demo-canvas-app@0.5.0-canary.542.e86662d3c5ab7e114b7f4756ae56e4dec468ee24.0
npm install @sberdevices/plasma-icons@1.25.0-canary.542.e86662d3c5ab7e114b7f4756ae56e4dec468ee24.0
npm install @sberdevices/plasma-ui@1.29.0-canary.542.e86662d3c5ab7e114b7f4756ae56e4dec468ee24.0
npm install @sberdevices/plasma-web@1.27.0-canary.542.e86662d3c5ab7e114b7f4756ae56e4dec468ee24.0
npm install @sberdevices/plasma-sb-utils@0.10.0-canary.542.e86662d3c5ab7e114b7f4756ae56e4dec468ee24.0
yarn add …
```
=> feat(demo-canvas-app): Added Switch to PickersPage

packages/plasma-ui/src/utils/deviceDetection.ts
<details>
<br />
```bash
npm install @sberdevices/showcase@0.34.0-canary.546.fb518e5dafb90d4c20c661a996379c55728a9291.0
npm install @sberdevices/demo-canvas-app@0.6.0-canary.546.fb518e5dafb90d4c20c661a996379c55728a9291.0
npm install @sberdevices/plasma-ui@1.30.0-canary.546.fb518e5dafb90d4c20c661a996379c55728a9291.0
npm install @sberdevices/plasma-web@1.28.0-canary.546.fb518e5dafb90d4c20c661a996379c55728a9291.0
yarn add @sberdevices/showcase@0.34.0-canary.546.fb518e5dafb90d4c20c661a996379c55728a9291.0
yarn add @sberdevices/demo-canvas-app@0.6.0-canary.546.fb518e5dafb90d4c20c661a996379c55728a9291.0
yarn add @sberdevices/plasma-ui@1.30.0-canary.546.fb518e5dafb90d4c20c661a …
```
=> feat(plasma-ui): Detect SberBoxTop

packages/plasma-ui/.storybook/preview.js, packages/plasma-web/.storybook/preview.js
<details>
<br />
```bash
npm install @sberdevices/showcase@0.34.1-canary.547.2a82ed5803fd6e209fc89d7f4fa14171df4d6bec.0
npm install @sberdevices/demo-canvas-app@0.6.1-canary.547.2a82ed5803fd6e209fc89d7f4fa14171df4d6bec.0
npm install @sberdevices/plasma-ui@1.30.1-canary.547.2a82ed5803fd6e209fc89d7f4fa14171df4d6bec.0
npm install @sberdevices/plasma-web@1.28.1-canary.547.2a82ed5803fd6e209fc89d7f4fa14171df4d6bec.0
yarn add @sberdevices/showcase@0.34.1-canary.547.2a82ed5803fd6e209fc89d7f4fa14171df4d6bec.0
yarn add @sberdevices/demo-canvas-app@0.6.1-canary.547.2a82ed5803fd6e209fc89d7f4fa14171df4d6bec.0
yarn add @sberdevices/plasma-ui@1.30.1-canary.547.2a82ed5803fd6e209fc89d7 …
```
=> fix(plasma-ui, plasma-web): toolbar buttons return

.stylelintrc.js, docs/showcase/src/helpers/Showcase.tsx, packages/plasma-ui/src/components/Header/HeaderButton.tsx, packages/plasma-web/src/components/Badge/Badge.tsx, packages/plasma-web/src/components/Button/Button.tsx, packages/plasma-web/src/components/Grid/Container.tsx, packages/plasma-web/src/components/Modal/Modal.tsx, packages/plasma-web/src/components/Modal/ModalView.tsx, packages/plasma-web/src/helpers/PaletteGrid.tsx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.34.2-canary.537.29f13b261dcd8df2b6d0e7d2c257b6fcd509fb73.0
npm install @sberdevices/demo-canvas-app@0.6.2-canary.537.29f13b261dcd8df2b6d0e7d2c257b6fcd509fb73.0
npm install @sberdevices/plasma-ui@1.30.2-canary.537.29f13b261dcd8df2b6d0e7d2c257b6fcd509fb73.0
npm install @sberdevices/plasma-web@1.28.2-canary.537.29f13b261dcd8df2b6d0e7d2c257b6fcd509fb73.0
yarn add @sberdevices/showcase@0.34.2-canary.537.29f13b261dcd8df2b6d0e7d2c257b6fcd509fb73.0
yarn add @sberdevices/demo-canvas-app@0.6.2-canary.537.29f13b261dcd8df2b6d0e7d2c257b6fcd509fb73.0
yarn add @sberdevices/plasma-ui@1.30.2-canary.537.29f13b261dcd8df2b6d0e7d …
```
=> fix: remove double ampersands

docs/showcase/.storybook/preview.js, docs/showcase/src/ui/Header.stories.tsx, packages/plasma-icons/src/Icon.assets/ChevronDown.tsx, packages/plasma-icons/src/Icon.assets/ChevronUp.tsx, packages/plasma-ui/src/components/Header/Header.stories.tsx, packages/plasma-ui/src/components/Header/Header.tsx, packages/plasma-ui/src/components/Header/HeaderBack.tsx, packages/plasma-ui/src/components/Header/HeaderLogo.tsx, packages/plasma-ui/src/components/Header/HeaderMinimize.tsx, packages/plasma-ui/src/components/Header/HeaderRoot.tsx, packages/plasma-ui/src/components/Header/HeaderTitleWrapper.tsx, packages/plasma-ui/src/components/Header/index.ts, packages/plasma-ui/src/components/TextBox/TextBox.tsx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.36.0-canary.551.7be608480d78fc3710df4b3aaac94ffe39bd27c8.0
npm install @sberdevices/demo-canvas-app@0.8.0-canary.551.7be608480d78fc3710df4b3aaac94ffe39bd27c8.0
npm install @sberdevices/plasma-icons@1.26.0-canary.551.7be608480d78fc3710df4b3aaac94ffe39bd27c8.0
npm install @sberdevices/plasma-ui@1.31.0-canary.551.7be608480d78fc3710df4b3aaac94ffe39bd27c8.0
npm install @sberdevices/plasma-web@1.30.0-canary.551.7be608480d78fc3710df4b3aaac94ffe39bd27c8.0
yarn add @sberdevices/showcase@0.36.0-canary.551.7be608480d78fc3710df4b3aaac94ffe39bd27c8.0
yarn add @sberdevices/demo-canvas-app@0.8.0-canary.551.7be608480d78fc371 …
```
=> feat: header minimize & layout

packages/plasma-core/src/components/Image/Image.tsx, packages/plasma-ui/src/components/Image/Image.stories.tsx, packages/plasma-web/src/components/Image/Image.stories.tsx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.40.1-canary.620.90449a9d616ada58f690d4ceaa49d67aafafdd7d.0
npm install @sberdevices/demo-canvas-app@0.12.1-canary.620.90449a9d616ada58f690d4ceaa49d67aafafdd7d.0
npm install @sberdevices/plasma-core@1.21.1-canary.620.90449a9d616ada58f690d4ceaa49d67aafafdd7d.0
npm install @sberdevices/plasma-icons@1.30.1-canary.620.90449a9d616ada58f690d4ceaa49d67aafafdd7d.0
npm install @sberdevices/plasma-tokens@1.10.1-canary.620.90449a9d616ada58f690d4ceaa49d67aafafdd7d.0
npm install @sberdevices/plasma-ui@1.35.1-canary.620.90449a9d616ada58f690d4ceaa49d67aafafdd7d.0
npm install …
```
=> fix(plasma-core): Image: add role attr

examples/demo-canvas-app/pages/_app.tsx, examples/demo-canvas-app/pages/index.tsx, examples/demo-canvas-app/pages/test/components/carousel.tsx, examples/demo-canvas-app/pages/test/components/grid.tsx, examples/demo-canvas-app/pages/test/components/pickers.tsx, examples/demo-canvas-app/pages/test/components/switch.tsx, examples/demo-canvas-app/pages/test/components/text-field.tsx, examples/demo-canvas-app/pages/test/components/toast.tsx, packages/plasma-core/src/hooks/index.ts, packages/plasma-core/src/hooks/useIsomorphicLayoutEffect.ts, packages/plasma-core/src/utils/canUseDOM.ts, packages/plasma-core/src/utils/index.ts, packages/plasma-ui/src/components/Grid/Container.tsx, packages/plasma-ui/src/components/Pickers/DatePicker.tsx, packages/plasma-ui/src/components/Pickers/TimePicker.tsx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.41.0-canary.607.9f6027b84a2ba7ad5bd6c3515ce14edea4c69414.0
npm install @sberdevices/demo-canvas-app@0.13.0-canary.607.9f6027b84a2ba7ad5bd6c3515ce14edea4c69414.0
npm install @sberdevices/plasma-core@1.22.0-canary.607.9f6027b84a2ba7ad5bd6c3515ce14edea4c69414.0
npm install @sberdevices/plasma-icons@1.31.0-canary.607.9f6027b84a2ba7ad5bd6c3515ce14edea4c69414.0
npm install @sberdevices/plasma-ui@1.36.0-canary.607.9f6027b84a2ba7ad5bd6c3515ce14edea4c69414.0
npm install @sberdevices/plasma-web@1.35.0-canary.607.9f6027b84a2ba7ad5bd6c3515ce14edea4c69414.0
npm install …
```
=> fix: Execution layout effect on server

packages/plasma-ui/src/mixins/index.ts, packages/plasma-ui/src/mixins/mixins.stories.mdx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.42.0-canary.629.3fcca3ed2de92a5301f926c32f5a7c3f4270ba13.0
npm install @sberdevices/demo-canvas-app@0.14.0-canary.629.3fcca3ed2de92a5301f926c32f5a7c3f4270ba13.0
npm install @sberdevices/plasma-icons@1.32.0-canary.629.3fcca3ed2de92a5301f926c32f5a7c3f4270ba13.0
npm install @sberdevices/plasma-ui@1.37.0-canary.629.3fcca3ed2de92a5301f926c32f5a7c3f4270ba13.0
npm install @sberdevices/plasma-web@1.36.0-canary.629.3fcca3ed2de92a5301f926c32f5a7c3f4270ba13.0
npm install @sberdevices/plasma-sb-utils@0.16.0-canary.629.3fcca3ed2de92a5301f926c32f5a7c3f4270ba13.0
yarn add …
```
=> feat(plasma-ui): Add mixin reexports from core

packages/plasma-core/src/components/Tabs/Tabs.tsx, packages/plasma-ui/src/components/Tabs/TabItem.tsx, packages/plasma-ui/src/components/Tabs/Tabs.stories.tsx, packages/plasma-ui/src/components/Tabs/Tabs.tsx, packages/plasma-ui/src/components/Tabs/TabsContainer.tsx, packages/plasma-ui/src/components/Tabs/TabsContext.tsx, packages/plasma-ui/src/components/Tabs/TabsSlider.tsx, packages/plasma-ui/src/components/Tabs/index.ts
<details>
<br />
```bash
npm install @sberdevices/showcase@0.43.0-canary.593.e7a351c320f68c3d4fac756ede6cd837d48fb4c2.0
npm install @sberdevices/demo-canvas-app@0.15.0-canary.593.e7a351c320f68c3d4fac756ede6cd837d48fb4c2.0
npm install @sberdevices/plasma-core@1.23.0-canary.593.e7a351c320f68c3d4fac756ede6cd837d48fb4c2.0
npm install @sberdevices/plasma-icons@1.33.0-canary.593.e7a351c320f68c3d4fac756ede6cd837d48fb4c2.0
npm install @sberdevices/plasma-ui@1.38.0-canary.593.e7a351c320f68c3d4fac756ede6cd837d48fb4c2.0
npm install @sberdevices/plasma-web@1.37.0-canary.593.e7a351c320f68c3d4fac756ede6cd837d48fb4c2.0
npm install …
```
=> feat(plasma-ui): tabs animation added

packages/plasma-ui/src/components/Marquee/Marquee.stories.tsx, packages/plasma-ui/src/components/Marquee/Marquee.tsx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.43.1-canary.618.4bdd90f37d94cd9db958bf6a887a9172b83ecf19.0
npm install @sberdevices/demo-canvas-app@0.15.1-canary.618.4bdd90f37d94cd9db958bf6a887a9172b83ecf19.0
npm install @sberdevices/plasma-icons@1.33.1-canary.618.4bdd90f37d94cd9db958bf6a887a9172b83ecf19.0
npm install @sberdevices/plasma-ui@1.38.1-canary.618.4bdd90f37d94cd9db958bf6a887a9172b83ecf19.0
npm install @sberdevices/plasma-web@1.37.1-canary.618.4bdd90f37d94cd9db958bf6a887a9172b83ecf19.0
npm install @sberdevices/plasma-sb-utils@0.17.1-canary.618.4bdd90f37d94cd9db958bf6a887a9172b83ecf19.0
yarn add …
```
=> fix(plasma-ui): marquee fix

packages/plasma-ui/src/components/Header/HeaderBack.tsx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.43.2-canary.634.86e2eb91f1d745a363e4411278e14b67ffd95b33.0
npm install @sberdevices/demo-canvas-app@0.15.2-canary.634.86e2eb91f1d745a363e4411278e14b67ffd95b33.0
npm install @sberdevices/plasma-ui@1.38.2-canary.634.86e2eb91f1d745a363e4411278e14b67ffd95b33.0
npm install @sberdevices/plasma-web@1.37.2-canary.634.86e2eb91f1d745a363e4411278e14b67ffd95b33.0
yarn add @sberdevices/showcase@0.43.2-canary.634.86e2eb91f1d745a363e4411278e14b67ffd95b33.0
yarn add @sberdevices/demo-canvas-app@0.15.2-canary.634.86e2eb91f1d745a363e4411278e14b67ffd95b33.0
yarn add @sberdevices/plasma-ui@1.38.2-canary.634.86e2eb91f1d745a363e44 …
```
=> fix(plasma-ui): fix vertical position of HeaderBack

docs/showcase/src/helpers/SliderDouble.tsx, docs/showcase/src/helpers/SliderShowcase.tsx, docs/showcase/src/helpers/SliderSingle.tsx, docs/showcase/src/helpers/index.ts, docs/showcase/src/showcase/Mobile/Controls.stories.tsx, docs/showcase/src/ui/Slider.stories.tsx, packages/plasma-ui/.storybook/main.js, packages/plasma-ui/package-lock.json, packages/plasma-ui/package.json, packages/plasma-ui/src/components/Slider/Double.tsx, packages/plasma-ui/src/components/Slider/Handle.tsx, packages/plasma-ui/src/components/Slider/Single.tsx, packages/plasma-ui/src/components/Slider/Slider.stories.tsx, packages/plasma-ui/src/components/Slider/Slider.tsx, packages/plasma-ui/src/components/Slider/SliderBase.tsx, packages/plasma-ui/src/components/Slider/index.ts, packages/plasma-ui/src/index.ts
<details>
<br />
```bash
npm install @sberdevices/showcase@0.44.0-canary.584.30b8eb7e5f99003121635c8de591bf0764474916.0
npm install @sberdevices/demo-canvas-app@0.16.0-canary.584.30b8eb7e5f99003121635c8de591bf0764474916.0
npm install @sberdevices/plasma-ui@1.39.0-canary.584.30b8eb7e5f99003121635c8de591bf0764474916.0
yarn add @sberdevices/showcase@0.44.0-canary.584.30b8eb7e5f99003121635c8de591bf0764474916.0
yarn add @sberdevices/demo-canvas-app@0.16.0-canary.584.30b8eb7e5f99003121635c8de591bf0764474916.0
yarn add @sberdevices/plasma-ui@1.39.0-canary.584.30b8eb7e5f99003121635c8de591bf0764474916.0
```
</details>
=> feat(plasma-ui): add Slider component

packages/plasma-ui/src/components/Skeleton/Skeleton.stories.tsx, packages/plasma-ui/src/components/Skeleton/index.ts, packages/plasma-ui/src/components/Stepper/Stepper.stories.tsx, packages/plasma-ui/src/components/Toast/Toast.stories.tsx, packages/plasma-ui/src/components/Toast/index.ts
UI:
- Skeleton
- Stepper
- Toast
=> chore(plasma-ui, plasma-web): knobs to controls migration - part 3

packages/plasma-core/src/components/Switch/Switch.tsx, packages/plasma-ui/src/components/Switch/Switch.stories.tsx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.45.0-canary.633.04a5152caf31b5e377d118cf30459e29ea53f078.0
npm install @sberdevices/demo-canvas-app@0.17.0-canary.633.04a5152caf31b5e377d118cf30459e29ea53f078.0
npm install @sberdevices/plasma-core@1.24.0-canary.633.04a5152caf31b5e377d118cf30459e29ea53f078.0
npm install @sberdevices/plasma-icons@1.34.0-canary.633.04a5152caf31b5e377d118cf30459e29ea53f078.0
npm install @sberdevices/plasma-ui@1.40.0-canary.633.04a5152caf31b5e377d118cf30459e29ea53f078.0
npm install @sberdevices/plasma-web@1.38.0-canary.633.04a5152caf31b5e377d118cf30459e29ea53f078.0
npm install …
```
=> feat: A11y Switch

packages/plasma-core/src/components/Switch/Switch.tsx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.47.0-canary.650.301116efafba961f20ac71b158c7dedef514f793.0
npm install @sberdevices/demo-canvas-app@0.19.0-canary.650.301116efafba961f20ac71b158c7dedef514f793.0
npm install @sberdevices/plasma-core@1.26.0-canary.650.301116efafba961f20ac71b158c7dedef514f793.0
npm install @sberdevices/plasma-icons@1.36.0-canary.650.301116efafba961f20ac71b158c7dedef514f793.0
npm install @sberdevices/plasma-tokens-b2c@0.5.0-canary.650.301116efafba961f20ac71b158c7dedef514f793.0
npm install @sberdevices/plasma-tokens-web@1.11.0-canary.650.301116efafba961f20ac71b158c7dedef514f793.0
npm install …
```
=> feat(plasma-ui): Switch add readOnly prop

packages/plasma-web/src/components/Tabs/Tabs.stories.tsx, packages/plasma-web/src/components/TextArea/TextArea.stories.tsx, packages/plasma-web/src/helpers/disableProps.tsx, packages/plasma-web/src/helpers/index.ts
=> docs(plasma-web): knobs to controls migration - web - part 3

packages/plasma-core/jest.config.ts, packages/plasma-core/package-lock.json, packages/plasma-core/package.json, packages/plasma-core/src/utils/__tests__/formatters.test.ts, packages/plasma-core/src/utils/formatters.ts, packages/plasma-core/tsconfig.json
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.21.1-canary.693.6ef005876432aa2f8fc569626e71d6a4c7e56379.0
npm install @sberdevices/plasma-core@1.27.1-canary.693.6ef005876432aa2f8fc569626e71d6a4c7e56379.0
npm install @sberdevices/plasma-icons@1.38.1-canary.693.6ef005876432aa2f8fc569626e71d6a4c7e56379.0
npm install @sberdevices/plasma-ui@1.44.1-canary.693.6ef005876432aa2f8fc569626e71d6a4c7e56379.0
npm install @sberdevices/plasma-web@1.42.1-canary.693.6ef005876432aa2f8fc569626e71d6a4c7e56379.0
npm install @sberdevices/plasma-sb-utils@0.22.1-canary.693.6ef005876432aa2f8fc569626e71d6a4c7e56379.0
npm install …
```
=> fix(plasma-core): fix monthName formatter

packages/plasma-web/src/components/Select/Select.stories.tsx, packages/plasma-web/src/components/Switch/Switch.stories.tsx, packages/plasma-web/src/components/TextField/TextField.stories.tsx
Web:
- Select
- Switch
- TextField
Relates to https://github.com/sberdevices/plasma/pull/661
=> docs(plasma-web): knobs to controls migration - web - part 3-2

packages/plasma-ui/src/components/Stepper/Stepper.stories.tsx, packages/plasma-ui/src/components/Stepper/Stepper.tsx, packages/plasma-ui/src/components/Stepper/StepperValue.tsx
<details>
<br />
```bash
npm install @sberdevices/plasma-docs@0.1.0-canary.675.05ef4ee2dc2b2a8bdbda06f657321e0c60caf96c.0
npm install @sberdevices/demo-canvas-app@0.23.0-canary.675.05ef4ee2dc2b2a8bdbda06f657321e0c60caf96c.0
npm install @sberdevices/plasma-ui@1.46.0-canary.675.05ef4ee2dc2b2a8bdbda06f657321e0c60caf96c.0
npm install @sberdevices/plasma-web@1.44.0-canary.675.05ef4ee2dc2b2a8bdbda06f657321e0c60caf96c.0
npm install @sberdevices/extract-sb-docgen-info@0.1.0-canary.675.05ef4ee2dc2b2a8bdbda06f657321e0c60caf96c.0
npm install @sberdevices/plasma-sb-utils@0.24.0-canary.675.05ef4ee2dc2b2a8bdbda06f657321e0c60caf96c.0
npm install …
```
=> feat(plasma-ui): value format for `Stepper` added

packages/plasma-web/src/components/Badge/Badge.stories.tsx, packages/plasma-web/src/components/Image/Image.stories.tsx, packages/plasma-web/src/components/Price/Price.stories.tsx, packages/plasma-web/src/components/Spinner/Spinner.stories.tsx, packages/plasma-web/src/components/Tooltip/Tooltip.stories.tsx
Web:
- Tooltip
- Badge
- Image
- Price
- Spinner
=> chore(plasma-ui, plasma-web): knobs to controls migration - web - part 4

packages/plasma-web/src/components/Notification/Notification.stories.tsx, packages/plasma-web/src/components/PaginationDots/PaginationDots.stories.tsx, packages/plasma-web/src/components/Progress/Progress.stories.tsx, packages/plasma-web/src/components/Radiobox/Radiobox.stories.tsx
Web:
- Notification
- PaginationDots
- Progress
- Radiobox
=> chore(plasma-ui, plasma-web): knobs to controls migration - web - part 2

packages/plasma-ui/src/components/Card/Card.stories.tsx, packages/plasma-ui/src/components/Carousel/Carousel.stories.tsx, packages/plasma-ui/src/components/Cell/Cell.stories.tsx, packages/plasma-ui/src/components/Header/Header.stories.tsx, packages/plasma-ui/src/components/Pickers/Pickers.stories.tsx, packages/plasma-ui/src/components/Pickers/TimePicker.tsx, packages/plasma-ui/src/helpers/StoryDecorators.tsx
UI:
- Card
- Carousel
- Cell
- Header
- Pickers
<details>
<br />
```bash
npm install @sberdevices/plasma-docs@0.1.2-canary.647.7c6d3ef0b3864e1782596c0623579177ba371c1a.0
npm install @sberdevices/demo-canvas-app@0.23.2-canary.647.7c6d3ef0b3864e1782596c0623579177ba371c1a.0
npm install @sberdevices/plasma-icons@1.39.2-canary.647.7c6d3ef0b3864e1782596c0623579177ba371c1a.0
npm install @sberdevices/plasma-tokens-b2c@0.5.2-canary.647.7c6d3ef0b3864e1782596c0623579177ba371c1a.0
npm install @sberdevices/plasma-tokens-web@1.11.2-canary.647.7c6d3ef0b3864e1782596c0623579177ba371c1a.0
npm install @sberdevices/plasma-ui@1.46.2-canary.647.7c6d3ef0b3864e1782596c0623579177ba371c1a.0 …
```
=> chore(plasma-ui): knobs to controls migration - part 4

packages/plasma-web/src/components/Button/Button.stories.tsx, packages/plasma-web/src/components/Carousel/Carousel.stories.tsx, packages/plasma-web/src/components/Checkbox/Checkbox.stories.tsx, packages/plasma-web/src/components/Modal/Modal.stories.tsx
Web: 
- Button
- Carousel
- Checkbox
- Modal
=> chore(plasma-ui, plasma-web): knobs to controls migration - web - part 1

packages/plasma-core/src/components/Badge/Badge.tsx
<details>
<br />
```bash
npm install @sberdevices/plasma-docs@0.1.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
npm install @sberdevices/demo-canvas-app@0.23.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
npm install @sberdevices/plasma-core@1.27.3-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
npm install @sberdevices/plasma-icons@1.39.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
npm install @sberdevices/plasma-tokens-b2c@0.5.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
npm install @sberdevices/plasma-tokens-web@1.11.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
npm install …
```
=> fix: Display `inline-flex` for `Badge`

packages/plasma-core/src/components/Button/Button.tsx, packages/plasma-core/src/mixins/applyView.ts, packages/plasma-web/.storybook/preview.js, packages/plasma-web/src/components/Button/Button.stories.tsx, packages/plasma-web/src/components/Button/Button.tsx
<details>
<br />
```bash
npm install @sberdevices/plasma-docs@0.1.4-canary.703.0a3c2d6e68764f8e41eb82d87cf61236ee83b258.0
npm install @sberdevices/demo-canvas-app@0.23.4-canary.703.0a3c2d6e68764f8e41eb82d87cf61236ee83b258.0
npm install demo-tokens@0.6.1-canary.703.0a3c2d6e68764f8e41eb82d87cf61236ee83b258.0
npm install @sberdevices/plasma-colors@0.1.2-canary.703.0a3c2d6e68764f8e41eb82d87cf61236ee83b258.0
npm install @sberdevices/plasma-core@1.27.4-canary.703.0a3c2d6e68764f8e41eb82d87cf61236ee83b258.0
npm install @sberdevices/plasma-icons@1.39.4-canary.703.0a3c2d6e68764f8e41eb82d87cf61236ee83b258.0
npm install @sberdevices/plasma-tokens-b2c@0.5.3-canary.703.0a3c2d6e68764 …
```
=> fix(plasma-web): Collision of `Button` and global custom css

packages/plasma-basic-template/template/config-overrides.js
<details>
<br />
```bash
npm install @sberdevices/cra-template-plasma-basic-template@1.2.1-canary.810.b84f9be2ec37fd374e00774d6a1490af847da9af.0
npm install @sberdevices/cra-template-plasma-shop-template@1.2.1-canary.810.b84f9be2ec37fd374e00774d6a1490af847da9af.0
yarn add @sberdevices/cra-template-plasma-basic-template@1.2.1-canary.810.b84f9be2ec37fd374e00774d6a1490af847da9af.0
yarn add @sberdevices/cra-template-plasma-shop-template@1.2.1-canary.810.b84f9be2ec37fd374e00774d6a1490af847da9af.0
```
</details>
=> fix(plasma-basic-template): code styles

packages/plasma-temple/package.json
<details>
<br />
```bash
npm install @sberdevices/cra-template-plasma-basic-template@2.0.0-canary.818.d6a534a247d07d57048c9241539262d831a35ded.0
npm install @sberdevices/cra-template-plasma-shop-template@2.0.0-canary.818.d6a534a247d07d57048c9241539262d831a35ded.0
npm install @sberdevices/plasma-temple@1.0.0-canary.818.d6a534a247d07d57048c9241539262d831a35ded.0
yarn add @sberdevices/cra-template-plasma-basic-template@2.0.0-canary.818.d6a534a247d07d57048c9241539262d831a35ded.0
yarn add @sberdevices/cra-template-plasma-shop-template@2.0.0-canary.818.d6a534a247d07d57048c9241539262d831a35ded.0
yarn add @sberdevices/plasma-temple@1.0.0-canary.818.d6a534a247d07d57048c92415392 …
```
=> feat(plasma-temple)!: major release

packages/plasma-temple/src/pages/CartPage/CartPage.tsx, packages/plasma-temple/src/pages/CartPage/components/CartItem/CartItem@common.tsx, packages/plasma-temple/src/pages/CartPage/components/CartItem/CartItem@mobile.tsx, packages/plasma-temple/src/pages/CartPage/components/CartItem/CartItem@sberbox.tsx, packages/plasma-temple/src/pages/CartPage/components/CartItem/CartItem@sberportal.tsx, packages/plasma-temple/src/pages/CartPage/components/CartItemList/CartItemList@common.tsx, packages/plasma-temple/src/pages/CartPage/components/CartItemList/CartItemList@mobile.tsx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.27.0-canary.814.e9ea4090bc4c0bfa0b281121e80231d0129ac5f0.0
npm install @sberdevices/plasma-b2c@1.3.0-canary.814.e9ea4090bc4c0bfa0b281121e80231d0129ac5f0.0
npm install @sberdevices/cra-template-plasma-basic-template@2.1.0-canary.814.e9ea4090bc4c0bfa0b281121e80231d0129ac5f0.0
npm install @sberdevices/plasma-icons@1.43.0-canary.814.e9ea4090bc4c0bfa0b281121e80231d0129ac5f0.0
npm install @sberdevices/cra-template-plasma-shop-template@2.1.0-canary.814.e9ea4090bc4c0bfa0b281121e80231d0129ac5f0.0
npm install @sberdevices/plasma-temple@1.1.0-canary.814.e9ea4090bc4c0bfa0b281121e80231d0129ac5f0.0
npm install …
```
=> feat(plasma-temple): opening item from cart

packages/plasma-temple/src/components/Page/Page.tsx, packages/plasma-temple/src/components/Page/types.ts
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.27.1-canary.820.55e5a45c862207cd1380ba8352bd152f0884bdb4.0
npm install @sberdevices/plasma-b2c@1.3.1-canary.820.55e5a45c862207cd1380ba8352bd152f0884bdb4.0
npm install @sberdevices/plasma-temple@1.1.1-canary.820.55e5a45c862207cd1380ba8352bd152f0884bdb4.0
npm install @sberdevices/plasma-ui@1.50.1-canary.820.55e5a45c862207cd1380ba8352bd152f0884bdb4.0
npm install @sberdevices/plasma-web@1.48.1-canary.820.55e5a45c862207cd1380ba8352bd152f0884bdb4.0
npm install @sberdevices/showcase@0.55.1-canary.820.55e5a45c862207cd1380ba8352bd152f0884bdb4.0
npm install …
```
=> fix(plasma-temple): fix page types

examples/demo-canvas-app/package.json
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.27.2-canary.826.994f19977594be6a36129aec57a0da158ef336cd.0
npm install @sberdevices/plasma-b2c@1.3.2-canary.826.994f19977594be6a36129aec57a0da158ef336cd.0
npm install @sberdevices/plasma-core@1.29.1-canary.826.994f19977594be6a36129aec57a0da158ef336cd.0
npm install @sberdevices/plasma-icons@1.43.1-canary.826.994f19977594be6a36129aec57a0da158ef336cd.0
npm install @sberdevices/plasma-ui@1.50.2-canary.826.994f19977594be6a36129aec57a0da158ef336cd.0
npm install @sberdevices/plasma-web@1.48.2-canary.826.994f19977594be6a36129aec57a0da158ef336cd.0
npm install …
```
=> fix: dummy-release

lerna.json, packages/plasma-core/src/components/Badge/Badge.component-test.tsx, packages/plasma-ui/src/components/Badge/Badge.component-test.tsx, packages/plasma-web/src/components/Badge/Badge.component-test.tsx, utils/plasma-cy-utils/src/CypressHelpers.tsx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.28.0-canary.824.06249387fd557ce3d91f2a8df7e780acea7cc020.0
npm install @sberdevices/plasma-b2c@1.4.0-canary.824.06249387fd557ce3d91f2a8df7e780acea7cc020.0
npm install @sberdevices/plasma-core@1.30.0-canary.824.06249387fd557ce3d91f2a8df7e780acea7cc020.0
npm install @sberdevices/plasma-icons@1.44.0-canary.824.06249387fd557ce3d91f2a8df7e780acea7cc020.0
npm install @sberdevices/plasma-ui@1.51.0-canary.824.06249387fd557ce3d91f2a8df7e780acea7cc020.0
npm install @sberdevices/plasma-web@1.49.0-canary.824.06249387fd557ce3d91f2a8df7e780acea7cc020.0
npm install …
```
=> fix(plasma-cy-utils): padMe

packages/plasma-shop-template/template.json, packages/plasma-shop-template/template/src/App.tsx, packages/plasma-shop-template/template/src/pages/Catalog/initCatalogState.ts, packages/plasma-temple/src/hooks/useSpatNav.ts, packages/plasma-temple/src/pages/CartPage/components/CartItem/CartItem@common.tsx, packages/plasma-temple/src/pages/CartPage/components/CartItemList/CartItemList@common.tsx
<details>
<br />
```bash
npm install @sberdevices/cra-template-plasma-shop-template@2.1.1-canary.813.cb466577fadf264be732b9cde91f39c8ea323c79.0
npm install @sberdevices/plasma-temple@1.1.3-canary.813.cb466577fadf264be732b9cde91f39c8ea323c79.0
yarn add @sberdevices/cra-template-plasma-shop-template@2.1.1-canary.813.cb466577fadf264be732b9cde91f39c8ea323c79.0
yarn add @sberdevices/plasma-temple@1.1.3-canary.813.cb466577fadf264be732b9cde91f39c8ea323c79.0
```
</details>
=> fix(plasma-temple): fix cart scroll

packages/plasma-temple/src/components/HeroSlide/HeroSlide@sberbox.tsx, packages/plasma-temple/src/components/HeroSlide/HeroSlide@sberportal.tsx
Исправления опечаток в стилях HeroSlide
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.28.1-canary.834.5e408309dc3d0048b0afa89e3414875b1e9a7278.0
npm install @sberdevices/plasma-b2c@1.5.1-canary.834.5e408309dc3d0048b0afa89e3414875b1e9a7278.0
npm install @sberdevices/plasma-core@1.30.1-canary.834.5e408309dc3d0048b0afa89e3414875b1e9a7278.0
npm install @sberdevices/plasma-icons@1.44.1-canary.834.5e408309dc3d0048b0afa89e3414875b1e9a7278.0
npm install @sberdevices/plasma-temple@1.1.4-canary.834.5e408309dc3d0048b0afa89e3414875b1e9a7278.0
npm install @sberdevices/plasma-ui@1.51.1-canary.834.5e408309dc3d0048b0afa89e3414875b1e9a7278.0
npm install …
```
=> fix(plasma-temple): Fix HeroSlide styles

packages/plasma-core/src/components/Toast/Toast.tsx, packages/plasma-core/src/components/Toast/Toast.types.ts, packages/plasma-core/src/components/Toast/ToastContext.tsx, packages/plasma-core/src/components/Toast/ToastController.tsx, packages/plasma-core/src/components/Toast/ToastProvider.tsx, packages/plasma-ui/.storybook/preview.js, packages/plasma-ui/src/components/Toast/Toast.stories.tsx, packages/plasma-ui/src/components/Toast/index.ts
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.38.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
npm install @sberdevices/plasma-b2c@1.17.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
npm install @sberdevices/plasma-core@1.35.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
npm install @sberdevices/plasma-icons@1.51.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
npm install @sberdevices/plasma-ui@1.61.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
npm install @sberdevices/plasma-web@1.57.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
npm install …
```
=> feat(plasma-ui): A11y for `Toast`

packages/plasma-b2c/src/components/PreviewGallery/PreviewGallery.stories.tsx, packages/plasma-b2c/src/components/PreviewGallery/PreviewGallery.tsx, packages/plasma-b2c/src/components/PreviewGallery/PreviewGalleryItemBase.tsx, packages/plasma-b2c/src/components/PreviewGallery/PreviewGalleryItems.tsx, packages/plasma-b2c/src/components/UploadVisual/UploadVisual.tsx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.40.0-canary.924.7406b4eba7954ee9e51ecd2dce3b7baed549370f.0
npm install @sberdevices/plasma-b2c@1.18.0-canary.924.7406b4eba7954ee9e51ecd2dce3b7baed549370f.0
npm install @sberdevices/plasma-ui@1.63.0-canary.924.7406b4eba7954ee9e51ecd2dce3b7baed549370f.0
npm install @sberdevices/showcase@0.72.0-canary.924.7406b4eba7954ee9e51ecd2dce3b7baed549370f.0
npm install @sberdevices/plasma-ui-docs@0.19.0-canary.924.7406b4eba7954ee9e51ecd2dce3b7baed549370f.0
npm install @sberdevices/plasma-website@0.6.0-canary.924.7406b4eba7954ee9e51ecd2dce3b7baed549370f.0
yarn add …
```
=> feat(plasma-b2c): PreviewGallery features

packages/plasma-b2c/src/mixins/index.ts, packages/plasma-core/src/mixins/applySpacing.ts, packages/plasma-core/src/mixins/index.ts
applySpacing не получается для адаптива использовать, хотелось бы spacing експортнуть и использовать напрямую
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.42.0-canary.936.5da1a1ac02a44c82150e89b2aba7d87bb09a1af3.0
npm install @sberdevices/plasma-b2c@1.20.0-canary.936.5da1a1ac02a44c82150e89b2aba7d87bb09a1af3.0
npm install @sberdevices/plasma-core@1.37.0-canary.936.5da1a1ac02a44c82150e89b2aba7d87bb09a1af3.0
npm install @sberdevices/plasma-icons@1.53.0-canary.936.5da1a1ac02a44c82150e89b2aba7d87bb09a1af3.0
npm install @sberdevices/plasma-ui@1.65.0-canary.936.5da1a1ac02a44c82150e89b2aba7d87bb09a1af3.0
npm install …
```
=> feat: export spacing

packages/plasma-icons/src/Icon.tsx, packages/plasma-icons/src/Icons/IconSpinner.tsx, packages/plasma-icons/src/Icons/IconVolumeMute.tsx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.43.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
npm install @sberdevices/plasma-b2c@1.21.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
npm install @sberdevices/plasma-icons@1.54.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
npm install @sberdevices/plasma-ui@1.66.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
npm install @sberdevices/plasma-web@1.60.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
npm install @sberdevices/showcase@0.75.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
npm install …
```
=> feat(plasma-icons): Remove `IconVolumeMute` and mark `IconSpinner` as deprecated 

packages/plasma-temple/package-lock.json, packages/plasma-temple/package.json, packages/plasma-temple/src/assistant.ts, packages/plasma-temple/src/components/GlobalStyles/GlobalStyles.tsx, packages/plasma-temple/src/hooks/useCharacter.ts, packages/plasma-temple/src/hooks/useVoiceNavigation.test.tsx, packages/plasma-temple/src/store/actions.ts, packages/plasma-temple/src/store/types.ts
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.5.0-canary.949.2af1bf35877a36c26ea621cbbeec0b9f3265cd5d.0
yarn add @sberdevices/plasma-temple@1.5.0-canary.949.2af1bf35877a36c26ea621cbbeec0b9f3265cd5d.0
```
</details>
=> feat(plasma-temple): update assistant-client version

packages/plasma-temple/src/pages/CartPage/CartPage.tsx, packages/plasma-temple/src/pages/CartPage/components/CartItem/CartItem@common.tsx, packages/plasma-temple/src/pages/CartPage/components/CartItem/CartItem@mobile.tsx, packages/plasma-temple/src/pages/CartPage/components/CartItem/CartItem@sberbox.tsx, packages/plasma-temple/src/pages/CartPage/components/CartItem/CartItem@sberportal.tsx, packages/plasma-temple/src/pages/CartPage/components/CartOrder/CartOrder@mobile.tsx, packages/plasma-temple/src/pages/CartPage/components/CartOrder/CartOrder@sberbox.tsx, packages/plasma-temple/src/pages/CartPage/components/CartOrder/CartOrder@sberportal.tsx, packages/plasma-temple/src/pages/CartPage/components/EmptyCart/EmptyCart@common.tsx, packages/plasma-temple/src/pages/CartPage/components/EmptyCart/EmptyCart@mobile.tsx
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.6.0-canary.954.17a4ebe0c649df9561fa4cdaab46af5fb9538af8.0
yarn add @sberdevices/plasma-temple@1.6.0-canary.954.17a4ebe0c649df9561fa4cdaab46af5fb9538af8.0
```
</details>
=> feat(plasma-temple): Add cart test attributes

packages/plasma-ui/src/components/Slider/SliderBase.tsx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.46.0-canary.955.6905312ee754764d84fe4bc2ffc9f579d29b9184.0
npm install @sberdevices/plasma-ui@1.69.0-canary.955.6905312ee754764d84fe4bc2ffc9f579d29b9184.0
npm install @sberdevices/showcase@0.79.0-canary.955.6905312ee754764d84fe4bc2ffc9f579d29b9184.0
npm install @sberdevices/plasma-ui-docs@0.29.0-canary.955.6905312ee754764d84fe4bc2ffc9f579d29b9184.0
yarn add @sberdevices/demo-canvas-app@0.46.0-canary.955.6905312ee754764d84fe4bc2ffc9f579d29b9184.0
yarn add @sberdevices/plasma-ui@1.69.0-canary.955.6905312ee754764d84fe4bc2ffc9f579d29b9184.0
yarn add …
```
=> feat(plasma-ui): Add default value in `Slider` component if theme context is undefined

packages/plasma-b2c/src/components/Slider/Double.tsx, packages/plasma-b2c/src/components/Slider/Handle.tsx, packages/plasma-b2c/src/components/Slider/Slider.stories.tsx, packages/plasma-ui/src/components/Slider/Double.tsx, packages/plasma-ui/src/components/Slider/Handle.tsx, packages/plasma-ui/src/components/Slider/Slider.stories.tsx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.46.1-canary.934.e38bc3b56262dfb4bd0ce9a789688a6e2c4a680b.0
npm install @sberdevices/plasma-b2c@1.25.1-canary.934.e38bc3b56262dfb4bd0ce9a789688a6e2c4a680b.0
npm install @sberdevices/plasma-ui@1.69.1-canary.934.e38bc3b56262dfb4bd0ce9a789688a6e2c4a680b.0
npm install @sberdevices/showcase@0.80.1-canary.934.e38bc3b56262dfb4bd0ce9a789688a6e2c4a680b.0
npm install @sberdevices/plasma-ui-docs@0.29.1-canary.934.e38bc3b56262dfb4bd0ce9a789688a6e2c4a680b.0
npm install @sberdevices/plasma-website@0.14.1-canary.934.e38bc3b56262dfb4bd0ce9a789688a6e2c4a680b.0
yarn add …
```
=> fix(plasma-ui, plasma-b2c): Fix intersection in `Slider` component

packages/plasma-temple/package-lock.json, packages/plasma-temple/package.json, packages/plasma-temple/src/components/AssistantActionConfirm/AssistantActionConfirm.tsx, packages/plasma-temple/src/components/AssistantSuggest/AssistantSuggest@sbebox.tsx, packages/plasma-temple/src/components/AssistantSuggest/AssistantSuggest@sbeportal.tsx, packages/plasma-temple/src/components/Form/components/Field.tsx, packages/plasma-temple/src/components/Header/Header.stories.tsx, packages/plasma-temple/src/components/Header/Header.tsx, packages/plasma-temple/src/components/Header/types.ts, packages/plasma-temple/src/components/Header/useHeaderProps.ts, packages/plasma-temple/src/components/Page/Page.tsx, packages/plasma-temple/src/components/Product/ProductPageSmamokat.stories.tsx, packages/plasma-temple/src/components/StateLayout/StateLayout@sberbox.tsx, packages/plasma-temple/src/components/StateLayout/StateLayout@sberportal.tsx, packages/plasma-temple/src/pages/CartPage/CartPage.tsx, packages/plasma-temple/src/pages/ConfirmOrderPage/ConfirmOrderPage.tsx, packages/plasma-temple/src/pages/GalleryPage/GalleryPage.tsx, packages/plasma-temple/src/pages/GalleryPage/components/Carousel.ts, packages/plasma-temple/src/pages/GridPage/GridPage.tsx, packages/plasma-temple/src/pages/ItemPage/ItemPage.tsx, packages/plasma-temple/src/pages/ShopLandingPage/ShopLandingPage.tsx, packages/plasma-temple/src/types.ts, packages/plasma-temple/tsconfig.json
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.9.0-canary.943.5d4730c2926ef9ab009d647138408533563c2106.0
yarn add @sberdevices/plasma-temple@1.9.0-canary.943.5d4730c2926ef9ab009d647138408533563c2106.0
```
</details>
=> feat(plasma-temple): add support new header api

packages/plasma-temple/src/components/Page/Page.tsx, packages/plasma-temple/src/pages/CartPage/types.ts
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.12.0-canary.971.697decec59a67c39eaaeb7fcf9d757cc414cc686.0
yarn add @sberdevices/plasma-temple@1.12.0-canary.971.697decec59a67c39eaaeb7fcf9d757cc414cc686.0
```
</details>
=> feat(plasma-temple): add promocode to cart

.github/workflows/documentation-main.yml
<details>
<br />
```bash
npm install @sberdevices/plasma-website@0.17.0-canary.988.a06bf344d719c56e0f6314089b52c25242cd786e.0
yarn add @sberdevices/plasma-website@0.17.0-canary.988.a06bf344d719c56e0f6314089b52c25242cd786e.0
```
</details>
=> feat: Add workflow_run for documentation-main workflow

examples/demo-canvas-app/pages/index.tsx, examples/demo-canvas-app/pages/test/components/checkbox.tsx, packages/plasma-b2c/src/components/Checkbox/Checkbox.stories.tsx, packages/plasma-core/src/components/Basebox/Basebox.tsx, packages/plasma-ui/src/components/Checkbox/Checkbox.stories.tsx, packages/plasma-web/src/components/Checkbox/Checkbox.stories.tsx, website/plasma-ui-docs/docs/components/Checkbox.mdx, website/plasma-web-docs/docs/components/Checkbox.mdx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.50.0-canary.969.cf9a990e7dd1a802f8dcfacd25b33637551c7c55.0
npm install @sberdevices/plasma-b2c@1.29.0-canary.969.cf9a990e7dd1a802f8dcfacd25b33637551c7c55.0
npm install @sberdevices/plasma-core@1.43.0-canary.969.cf9a990e7dd1a802f8dcfacd25b33637551c7c55.0
npm install @sberdevices/plasma-icons@1.60.0-canary.969.cf9a990e7dd1a802f8dcfacd25b33637551c7c55.0
npm install @sberdevices/plasma-temple@1.14.0-canary.969.cf9a990e7dd1a802f8dcfacd25b33637551c7c55.0
npm install @sberdevices/plasma-ui@1.73.0-canary.969.cf9a990e7dd1a802f8dcfacd25b33637551c7c55.0
npm install …
```
=> feat(plasma-core): Add ReactNode type for label field in `Checkbox` component 

packages/plasma-b2c/src/components/Radiobox/index.ts
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.51.0-canary.992.18ad2ff59b9f72936dc9f9dbfc6cee563e083353.0
npm install @sberdevices/plasma-b2c@1.30.0-canary.992.18ad2ff59b9f72936dc9f9dbfc6cee563e083353.0
npm install @sberdevices/plasma-core@1.44.0-canary.992.18ad2ff59b9f72936dc9f9dbfc6cee563e083353.0
npm install @sberdevices/plasma-icons@1.61.0-canary.992.18ad2ff59b9f72936dc9f9dbfc6cee563e083353.0
npm install @sberdevices/plasma-temple@1.15.0-canary.992.18ad2ff59b9f72936dc9f9dbfc6cee563e083353.0
npm install @sberdevices/plasma-ui@1.74.0-canary.992.18ad2ff59b9f72936dc9f9dbfc6cee563e083353.0
npm install …
```
=> feat(plasma-b2c): make RadioGroup public

packages/plasma-b2c/src/components/SSRProvider/index.ts, packages/plasma-b2c/src/index.ts
<details>
<br />
```bash
npm install @sberdevices/plasma-b2c@1.32.0-canary.1000.e4c619ddb38560174a2b4707f1a11353a36f47cc.0
npm install @sberdevices/showcase@0.87.0-canary.1000.e4c619ddb38560174a2b4707f1a11353a36f47cc.0
npm install @sberdevices/plasma-website@0.22.0-canary.1000.e4c619ddb38560174a2b4707f1a11353a36f47cc.0
yarn add @sberdevices/plasma-b2c@1.32.0-canary.1000.e4c619ddb38560174a2b4707f1a11353a36f47cc.0
yarn add @sberdevices/showcase@0.87.0-canary.1000.e4c619ddb38560174a2b4707f1a11353a36f47cc.0
yarn add @sberdevices/plasma-website@0.22.0-canary.1000.e4c619ddb38560174a2b4707f1a11353a36f47cc.0
```
</details>
=> feat(b2c): add SSRProvider

packages/plasma-ui/src/components/Pickers/Picker.tsx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.51.2-canary.1007.1ebda925a22abbd21d18a32b7b309c045dc04bd1.0
npm install @sberdevices/plasma-b2c@1.32.2-canary.1007.1ebda925a22abbd21d18a32b7b309c045dc04bd1.0
npm install @sberdevices/plasma-temple@1.16.1-canary.1007.1ebda925a22abbd21d18a32b7b309c045dc04bd1.0
npm install @sberdevices/plasma-ui@1.74.2-canary.1007.1ebda925a22abbd21d18a32b7b309c045dc04bd1.0
npm install @sberdevices/showcase@0.87.2-canary.1007.1ebda925a22abbd21d18a32b7b309c045dc04bd1.0
npm install @sberdevices/plasma-ui-docs@0.34.2-canary.1007.1ebda925a22abbd21d18a32b7b309c045dc04bd1.0
npm install …
```
=> fix(plasma-ui): Add scroll fix for `Picker` component

packages/plasma-tokens/design-language/src/DesignLanguage.ts
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.53.2-canary.1030.b50246f5c3cfaf5176c75d130c074d2b66d193f3.0
npm install @sberdevices/plasma-b2c@1.34.2-canary.1030.b50246f5c3cfaf5176c75d130c074d2b66d193f3.0
npm install @sberdevices/plasma-core@1.46.2-canary.1030.b50246f5c3cfaf5176c75d130c074d2b66d193f3.0
npm install @sberdevices/plasma-icons@1.63.2-canary.1030.b50246f5c3cfaf5176c75d130c074d2b66d193f3.0
npm install @sberdevices/plasma-temple@1.19.2-canary.1030.b50246f5c3cfaf5176c75d130c074d2b66d193f3.0
npm install @sberdevices/plasma-tokens@1.15.1-canary.1030.b50246f5c3cfaf5176c75d130c074d2b66d193f3.0
npm install …
```
=> fix(plasma-tokens): wrong primary/secondary tokens

packages/plasma-b2c/src/components/Notification/index.tsx, packages/plasma-web/src/components/Notification/index.tsx
<details>
<br />
```bash
npm install @sberdevices/plasma-b2c@1.34.3-canary.1029.368cec2272a9cea434578cdefa0612e8a7d11932.0
npm install @sberdevices/plasma-web@1.70.3-canary.1029.368cec2272a9cea434578cdefa0612e8a7d11932.0
npm install @sberdevices/showcase@0.89.3-canary.1029.368cec2272a9cea434578cdefa0612e8a7d11932.0
npm install @sberdevices/plasma-ui-docs@0.36.3-canary.1029.368cec2272a9cea434578cdefa0612e8a7d11932.0
npm install @sberdevices/plasma-web-docs@0.27.3-canary.1029.368cec2272a9cea434578cdefa0612e8a7d11932.0
npm install @sberdevices/plasma-website@0.24.3-canary.1029.368cec2272a9cea434578cdefa0612e8a7d11932.0
yarn add …
```
=> fix(plasma-b2c,plasma-web): Add re-export for `Notification` component

packages/plasma-web/src/components/Modal/Modal.component-test.tsx, packages/plasma-web/src/components/Modal/Modal.stories.tsx, packages/plasma-web/src/components/Modal/Modal.tsx, packages/plasma-web/src/components/Modal/ModalView.tsx, packages/plasma-web/src/components/Modal/ModalsContext.tsx
<details>
<br />
```bash
npm install @sberdevices/plasma-b2c@1.35.0-canary.1024.5175a0fbe8be719c84d27556b6a76ef51d8946c5.0
npm install @sberdevices/plasma-temple@1.20.0-canary.1024.5175a0fbe8be719c84d27556b6a76ef51d8946c5.0
npm install @sberdevices/plasma-web@1.71.0-canary.1024.5175a0fbe8be719c84d27556b6a76ef51d8946c5.0
npm install @sberdevices/showcase@0.90.0-canary.1024.5175a0fbe8be719c84d27556b6a76ef51d8946c5.0
npm install @sberdevices/plasma-ui-docs@0.37.0-canary.1024.5175a0fbe8be719c84d27556b6a76ef51d8946c5.0
npm install @sberdevices/plasma-web-docs@0.28.0-canary.1024.5175a0fbe8be719c84d27556b6a76ef51d8946c5.0
npm install …
```
=> fix: `Modal` fixes

packages/plasma-temple/package-lock.json, packages/plasma-temple/package.json, packages/plasma-temple/src/utils/getAssistantSmartAppInitialData.ts, packages/plasma-temple/src/utils/index.ts
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.21.0-canary.1043.af3188fee7b536692e4a4de971fb2f58b8752885.0
yarn add @sberdevices/plasma-temple@1.21.0-canary.1043.af3188fee7b536692e4a4de971fb2f58b8752885.0
```
</details>
=> feat(plasma-temple): Support for findInInitialData

packages/plasma-temple/src/components/StateLayout/StateLayout.tsx, packages/plasma-temple/src/components/StateLayout/StateLayout@common.tsx, packages/plasma-temple/src/components/StateLayout/StateLayout@mobile.tsx, packages/plasma-temple/src/components/StateLayout/StateLayout@sberbox.tsx, packages/plasma-temple/src/components/StateLayout/StateLayout@sberportal.tsx, packages/plasma-temple/src/registry/registry@sberbox.ts, packages/plasma-temple/src/registry/registry@sberportal.ts
Мобильная версия для `StateLayout`
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.23.0-canary.1004.7a0b23aa1a4025311e26d539d8d223b3b69c1345.0
yarn add @sberdevices/plasma-temple@1.23.0-canary.1004.7a0b23aa1a4025311e26d539d8d223b3b69c1345.0
```
</details>
=> feat(plasma-temple): Mobile StateLayout

packages/plasma-temple/src/components/index.ts
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.24.2-canary.1042.c7ea76e5995ec1d5a823d98419414ba27715c9af.0
yarn add @sberdevices/plasma-temple@1.24.2-canary.1042.c7ea76e5995ec1d5a823d98419414ba27715c9af.0
```
</details>
=> fix(plasma-temple): exports VideoPlayer component

packages/plasma-temple/package.json
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.27.1-canary.1065.2c9be97bde10a87a0dc68729d61ebeab052fd190.0
yarn add @sberdevices/plasma-temple@1.27.1-canary.1065.2c9be97bde10a87a0dc68729d61ebeab052fd190.0
```
</details>
=> plasma-temple: peer deps versions

packages/plasma-ui/src/components/Header/HeaderArrow.tsx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.58.4-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
npm install @sberdevices/plasma-b2c@1.39.7-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
npm install @sberdevices/plasma-core@1.49.4-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
npm install @sberdevices/plasma-icons@1.67.5-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
npm install @sberdevices/plasma-temple@1.29.2-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
npm install @sberdevices/plasma-tokens-b2c@0.8.1-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
npm install …
```
=> fix(plasma-ui): `HeaderArrow`: made unfocusable

packages/plasma-temple/package-lock.json, packages/plasma-temple/package.json, packages/plasma-temple/src/components/VideoPlayer/VideoPlayer.tsx, packages/plasma-temple/src/pages/VideoPage/VideoPage.tsx
Возможность добавлять css класс на видео в той фазе, когда показывается постер. Бывает полезно, например, если надо добавить блюр на постер в видео
<details>
<br />
```bash
npm install @sberdevices/plasma-b2c@1.41.0-canary.1103.d6814a0f3506e6c8267d343879eac60195d0cc3e.0
npm install @sberdevices/plasma-temple@1.31.0-canary.1103.d6814a0f3506e6c8267d343879eac60195d0cc3e.0
npm install @sberdevices/showcase@0.97.0-canary.1103.d6814a0f3506e6c8267d343879eac60195d0cc3e.0
npm install @sberdevices/plasma-website@0.31.0-canary.1103.d6814a0f3506e6c8267d343879eac60195d0cc3e.0
yarn add @sberdevices/plasma-b2c@1.41.0-canary.1103.d6814a0f3506e6c8267d343879eac60195d0cc3e.0
yarn add …
```
=> feat(plasma-temple): className for poster on VideoPage

packages/plasma-ui/package-lock.json, packages/plasma-ui/package.json, packages/plasma-ui/src/components/Tabs/TabsSlider.tsx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.59.4-canary.1118.c8b6853bdb4162b31255f117bbd17c944fb59a79.0
npm install @sberdevices/plasma-b2c@1.41.3-canary.1118.c8b6853bdb4162b31255f117bbd17c944fb59a79.0
npm install @sberdevices/plasma-core@1.49.8-canary.1118.c8b6853bdb4162b31255f117bbd17c944fb59a79.0
npm install @sberdevices/plasma-icons@1.67.9-canary.1118.c8b6853bdb4162b31255f117bbd17c944fb59a79.0
npm install @sberdevices/plasma-temple@1.31.3-canary.1118.c8b6853bdb4162b31255f117bbd17c944fb59a79.0
npm install @sberdevices/plasma-typo@0.2.4-canary.1118.c8b6853bdb4162b31255f117bbd17c944fb59a79.0
npm install …
```
=> fix(plasma-ui): fix slider size and offset when active tab size is changed

packages/plasma-core/src/components/PaginationDots/PaginationDots.tsx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.61.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
npm install @sberdevices/plasma-b2c@1.43.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
npm install @sberdevices/plasma-core@1.51.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
npm install @sberdevices/plasma-icons@1.69.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
npm install @sberdevices/plasma-temple@1.33.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
npm install @sberdevices/plasma-tokens-b2c@0.10.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
npm install …
```
=> feat: `PaginationDots`: made `aria-hidden=true` by default

packages/plasma-core/src/components/Tabs/TabItem.tsx, packages/plasma-core/src/components/Tabs/Tabs.component-test.tsx, packages/plasma-core/src/components/Tabs/createTabsController.tsx, packages/plasma-ui/src/components/Tabs/TabItem.tsx, packages/plasma-ui/src/components/Tabs/Tabs.stories.tsx, packages/plasma-ui/src/components/Tabs/Tabs.tsx, packages/plasma-ui/src/components/Tabs/TabsSlider.tsx, packages/plasma-ui/src/components/Tabs/TabsView.tsx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.61.1-canary.1116.8b7540359acfe94c5d209d754274115f10d73e0c.0
npm install @sberdevices/plasma-b2c@1.43.1-canary.1116.8b7540359acfe94c5d209d754274115f10d73e0c.0
npm install @sberdevices/plasma-core@1.51.1-canary.1116.8b7540359acfe94c5d209d754274115f10d73e0c.0
npm install @sberdevices/plasma-icons@1.69.1-canary.1116.8b7540359acfe94c5d209d754274115f10d73e0c.0
npm install @sberdevices/plasma-temple@1.33.1-canary.1116.8b7540359acfe94c5d209d754274115f10d73e0c.0
npm install @sberdevices/plasma-ui@1.84.1-canary.1116.8b7540359acfe94c5d209d754274115f10d73e0c.0
npm install …
```
=> fix(plasma-ui): correct Tabs disable state

packages/plasma-temple/package-lock.json, packages/plasma-temple/package.json, packages/plasma-temple/src/components/Product/Product.tsx, packages/plasma-temple/src/components/Product/Product@common.tsx, packages/plasma-temple/src/components/Product/ProductActionButton/ProductActionButton.tsx, packages/plasma-temple/src/components/Product/ProductDetails/ExpandableProductDetails/ExpandableProductDetails.tsx, packages/plasma-temple/src/components/Product/ProductDetails/ExpandableProductDetails/ExpandableProductDetails@common.tsx, packages/plasma-temple/src/components/Product/ProductDetails/ProductDetails.tsx, packages/plasma-temple/src/components/Product/ProductImage/ProductImage.tsx, packages/plasma-temple/src/components/Product/ProductImageSlider/ProductImageSlider.tsx, packages/plasma-temple/src/components/Product/ProductInfo/ProductInfo.tsx, packages/plasma-temple/src/components/Product/ProductInfo/ProductInfo@common.tsx, packages/plasma-temple/src/components/Product/ProductPrice/ProductPrice.tsx, packages/plasma-temple/src/components/Product/ProductPrice/ProductPrice@common.tsx, packages/plasma-temple/src/components/Product/ProductPrice/types.ts, packages/plasma-temple/src/components/Product/ProductRecommendations/ProductRecommendations.tsx, packages/plasma-temple/src/components/Product/ProductTitle/ProductTitle.tsx, packages/plasma-temple/src/components/Product/ProductTitle/types.ts, packages/plasma-temple/src/components/Product/ProductVariationSwitcher/ProductVariationSwitcher.tsx, website/plasma-temple-docs/docs/components/Product.mdx, website/plasma-temple-docs/package.json
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.36.0-canary.1110.c8387bf1fa7a4ef5a2fbc877f0bf869824c6c293.0
npm install @sberdevices/plasma-temple-docs@0.8.0-canary.1110.c8387bf1fa7a4ef5a2fbc877f0bf869824c6c293.0
yarn add @sberdevices/plasma-temple@1.36.0-canary.1110.c8387bf1fa7a4ef5a2fbc877f0bf869824c6c293.0
yarn add @sberdevices/plasma-temple-docs@0.8.0-canary.1110.c8387bf1fa7a4ef5a2fbc877f0bf869824c6c293.0
```
</details>
=> Product docs

packages/plasma-temple/src/components/index.ts, packages/plasma-temple/src/hooks/index.ts, packages/plasma-temple/src/pages/ItemPage/index.ts, packages/plasma-temple/src/utils/index.ts
Экспорты, необходимые для создания кастомного подобия ItemPage
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.37.0-canary.1125.b29b4cfc6f1b61ffbdad2329301246c155908232.0
yarn add @sberdevices/plasma-temple@1.37.0-canary.1125.b29b4cfc6f1b61ffbdad2329301246c155908232.0
```
</details>
=> feat(plasma-temple): Exports for custom ittem page

packages/plasma-b2c/src/components/TextArea/TextArea.stories.tsx, packages/plasma-b2c/src/components/TextArea/TextArea.tsx, packages/plasma-ui/src/components/TextArea/TextArea.stories.tsx, packages/plasma-ui/src/components/TextArea/TextArea.tsx, packages/plasma-web/src/components/TextArea/TextArea.stories.tsx, packages/plasma-web/src/components/TextArea/TextArea.tsx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.66.0-canary.1133.f3fc4a99469ffee4fd6479c8bde8eb0c216b79ea.0
npm install @sberdevices/plasma-b2c@1.50.0-canary.1133.f3fc4a99469ffee4fd6479c8bde8eb0c216b79ea.0
npm install @sberdevices/plasma-temple@1.42.0-canary.1133.f3fc4a99469ffee4fd6479c8bde8eb0c216b79ea.0
npm install @sberdevices/plasma-ui@1.89.0-canary.1133.f3fc4a99469ffee4fd6479c8bde8eb0c216b79ea.0
npm install @sberdevices/plasma-web@1.85.0-canary.1133.f3fc4a99469ffee4fd6479c8bde8eb0c216b79ea.0
npm install @sberdevices/showcase@0.106.0-canary.1133.f3fc4a99469ffee4fd6479c8bde8eb0c216b79ea.0
npm install …
```
=> feat: `TextArea` a11y improvements

actions/versionate-docs/package-lock.json, actions/versionate-docs/package.json, actions/versionate-docs/src/fs.ts, actions/versionate-docs/src/utils.test.ts, actions/versionate-docs/src/utils.ts
<details>
<br />
```bash
npm install @sberdevices/versionate-docs@0.3.0-canary.1147.fd747c7598af23b66655ff893ed61bd3872d44fc.0
yarn add @sberdevices/versionate-docs@0.3.0-canary.1147.fd747c7598af23b66655ff893ed61bd3872d44fc.0
```
</details>
=> feat(versionate-docs): Added versionArchived.json sort

website/plasma-ui-docs/docs/aml.mdx
второй кусочек https://github.com/sberdevices/plasma/pull/1137
<details>
<br />
```bash
npm install @sberdevices/plasma-ui-docs@0.55.0-canary.1151.ef3454436837879228c4588bf7b23fdc2f906250.0
yarn add @sberdevices/plasma-ui-docs@0.55.0-canary.1151.ef3454436837879228c4588bf7b23fdc2f906250.0
```
</details>
=> feat(aml): Cross reference with corresp. SM docs

packages/plasma-icons/.gitignore, packages/plasma-icons/package.json, packages/plasma-icons/src/scalable/Icon.assets.16/Video.tsx, packages/plasma-icons/src/scalable/Icon.assets.16/index.ts, packages/plasma-icons/src/scalable/Icon.assets.24/AttentionCircle.tsx, packages/plasma-icons/src/scalable/Icon.assets.24/index.ts, packages/plasma-icons/src/scalable/Icon.assets.36/AntennaCircle.tsx, packages/plasma-icons/src/scalable/Icon.assets.36/index.ts, packages/plasma-icons/src/scalable/Icon.tsx, packages/plasma-icons/src/scalable/IconRoot.tsx, packages/plasma-icons/src/scalable/Icons/IconAntennaCircle.tsx, packages/plasma-icons/src/scalable/Icons/IconAttentionCircle.tsx, packages/plasma-icons/src/scalable/Icons/IconVideo.tsx, packages/plasma-icons/src/scalable/index.ts
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.67.0-canary.1152.c5c4d21aacf86ce00e5cb4cbbabdb69418fed123.0
npm install @sberdevices/plasma-b2c@1.52.0-canary.1152.c5c4d21aacf86ce00e5cb4cbbabdb69418fed123.0
npm install @sberdevices/plasma-icons@1.72.0-canary.1152.c5c4d21aacf86ce00e5cb4cbbabdb69418fed123.0
npm install @sberdevices/plasma-temple@1.44.0-canary.1152.c5c4d21aacf86ce00e5cb4cbbabdb69418fed123.0
npm install @sberdevices/plasma-ui@1.90.0-canary.1152.c5c4d21aacf86ce00e5cb4cbbabdb69418fed123.0
npm install @sberdevices/plasma-web@1.87.0-canary.1152.c5c4d21aacf86ce00e5cb4cbbabdb69418fed123.0
npm install …
```
=> feat(plasma-icons): Add scalable icons prototype 

packages/plasma-web/src/components/Carousel/Carousel.tsx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.67.0-canary.1155.72c403de118d3d5ba4f882f15ddee41880ff2b4d.0
npm install @sberdevices/plasma-b2c@1.52.0-canary.1155.72c403de118d3d5ba4f882f15ddee41880ff2b4d.0
npm install @sberdevices/plasma-icons@1.72.0-canary.1155.72c403de118d3d5ba4f882f15ddee41880ff2b4d.0
npm install @sberdevices/plasma-temple@1.44.0-canary.1155.72c403de118d3d5ba4f882f15ddee41880ff2b4d.0
npm install @sberdevices/plasma-ui@1.90.0-canary.1155.72c403de118d3d5ba4f882f15ddee41880ff2b4d.0
npm install @sberdevices/plasma-web@1.87.0-canary.1155.72c403de118d3d5ba4f882f15ddee41880ff2b4d.0
npm install …
```
=> feat(plasma-web): Add ref to carousel

packages/plasma-temple/src/assistant.ts, packages/plasma-temple/src/index.ts
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.68.0-canary.1163.0f25b8958ff7d8bdf2c0a9a17395ab4416482594.0
npm install @sberdevices/plasma-b2c@1.54.0-canary.1163.0f25b8958ff7d8bdf2c0a9a17395ab4416482594.0
npm install @sberdevices/plasma-core@1.54.0-canary.1163.0f25b8958ff7d8bdf2c0a9a17395ab4416482594.0
npm install @sberdevices/plasma-icons@1.73.0-canary.1163.0f25b8958ff7d8bdf2c0a9a17395ab4416482594.0
npm install @sberdevices/plasma-temple@1.49.0-canary.1163.0f25b8958ff7d8bdf2c0a9a17395ab4416482594.0
npm install @sberdevices/plasma-ui@1.91.0-canary.1163.0f25b8958ff7d8bdf2c0a9a17395ab4416482594.0
npm install …
```
=> feat(plasma-temple): Assistant impovements

packages/plasma-temple/mobile/package.json, packages/plasma-temple/package.json, packages/plasma-temple/sberbox/package.json, packages/plasma-temple/sberportal/package.json, packages/plasma-temple/src/components/DeviceComponent/DeviceComponent.tsx, packages/plasma-temple/src/components/StateLayout/StateLayout.tsx, packages/plasma-temple/src/components/index@mobile.ts, packages/plasma-temple/src/components/index@sberbox.ts, packages/plasma-temple/src/components/index@sberportal.ts, packages/plasma-temple/src/index@mobile.ts, packages/plasma-temple/src/index@sberbox.ts, packages/plasma-temple/src/index@sberportal.ts
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.54.0-canary.1182.8d18f4bf6bfeeb247d2285ed07de0cd69919b4a5.0
yarn add @sberdevices/plasma-temple@1.54.0-canary.1182.8d18f4bf6bfeeb247d2285ed07de0cd69919b4a5.0
```
</details>
=> feat(plasma-temple): add device component

packages/plasma-temple/src/components/Page/Page.tsx, packages/plasma-temple/src/components/PlasmaApp/PlasmaApp.tsx, packages/plasma-temple/src/hooks/useInitializeAssistant.ts
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.55.0-canary.1176.b6d8876b73276c50f42c7373d64fe1dc72532909.0
yarn add @sberdevices/plasma-temple@1.55.0-canary.1176.b6d8876b73276c50f42c7373d64fe1dc72532909.0
```
</details>
=> feat(plasma-temple): onStart wait for character

packages/plasma-temple/src/components/Cart/Cart.tsx, packages/plasma-temple/src/components/Cart/Cart@common.tsx, packages/plasma-temple/src/components/Cart/Cart@mobile.tsx, packages/plasma-temple/src/components/Cart/Cart@sberbox.tsx, packages/plasma-temple/src/components/Cart/Cart@sberportal.tsx, packages/plasma-temple/src/components/Cart/CartItemCaption/CartItemCaption.tsx, packages/plasma-temple/src/components/Cart/CartItemList/CartItemList.tsx, packages/plasma-temple/src/components/Cart/CartOrder/CartOrder.tsx, packages/plasma-temple/src/components/Cart/CartOrder/CartOrder@mobile.tsx, packages/plasma-temple/src/components/Cart/CartOrder/CartOrder@sberbox.tsx, packages/plasma-temple/src/components/Cart/CartOrder/CartOrder@sberportal.tsx, packages/plasma-temple/src/components/Cart/index@mobile.ts, packages/plasma-temple/src/components/Cart/index@sberbox.ts, packages/plasma-temple/src/components/Cart/index@sberportal.ts, packages/plasma-temple/src/components/index@mobile.ts, packages/plasma-temple/src/components/index@sberbox.ts, packages/plasma-temple/src/components/index@sberportal.ts, packages/plasma-temple/src/pages/CartPage/CartPage.tsx
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.58.0-canary.1184.226276f9629b1fbc8aeabfc6bdc050ffce6c70fe.0
yarn add @sberdevices/plasma-temple@1.58.0-canary.1184.226276f9629b1fbc8aeabfc6bdc050ffce6c70fe.0
```
</details>
=> feat(plasma-temple): cart - exports by platforms
