- packages/ui/src/components/Card/index.ts
При импорте из корня любого компонента получаем ошибку:
```
./node_modules/@sberdevices/ui/components/Card/CardPrice.js
Module not found: Can't resolve '../../helpers/formatCurrency' in 'plasma-demo/node_modules/@sberdevices/ui/components/Card'
```
<details>
<br />
```bash
npm install @sberdevices/ui@0.20.1-canary.82.d5293ae70d9d9472accb8692185b10af187d72b1.0
yarn add @sberdevices/ui@0.20.1-canary.82.d5293ae70d9d9472accb8692185b10af187d72b1.0
```
</details>
> fix(ui): удалить CardPrice из поставки

- lerna.json
- package.json
Не знаю каким боком оно перестало работать или почему оно работало раньше,
но `lerna` перестала мочь достучаться до ручки /user:
```
lerna http fetch GET 403 https://registry.npmjs.org/-/npm/v1/user 199ms
403 Forbidden - GET https://registry.npmjs.org/-/npm/v1/user
lerna ERR! EWHOAMI Authentication error. Use `npm whoami` to troubleshoot.
```
в эту ручку lerna ходит вот тут: https://github.com/lerna/lerna/blob/72414ec1c679cf8a7ae4bfcefce52d50a6120a70/commands/publish/lib/get-profile-data.js#L11
туда нужно сходить чтобы получить имя пользователя npm O_o 
https://github.com/lerna/lerna/blob/72414ec1c679cf8a7ae4bfcefce52d50a6120a70/commands/publish/lib/get-npm-username.js#L10
и это нужно чтобы удостовериться что у пользователя есть права на паблишинг: …
> ci: disable lerna check for user auth

- packages/ui/src/components/Badge/Badge.tsx
Closes #85 
<details>
<br />
```bash
npm install @sberdevices/ui@0.20.1-canary.113.6ce3afc4a1b2e76dc7854f6919b33e21c562fea8.0
yarn add @sberdevices/ui@0.20.1-canary.113.6ce3afc4a1b2e76dc7854f6919b33e21c562fea8.0
```
</details>
> fix(ui): Исправлен отступ от иконки 4рх в Badge

- packages/plasma-icons/src/IconRoot.tsx
<details>
<br />
```bash
npm install @sberdevices/plasma-icons@0.2.1-canary.145.a8f010f7e72f4eaf55e848ecd0decccb4d07a4f1.0
npm install @sberdevices/ui@0.20.1-canary.145.a8f010f7e72f4eaf55e848ecd0decccb4d07a4f1.0
yarn add @sberdevices/plasma-icons@0.2.1-canary.145.a8f010f7e72f4eaf55e848ecd0decccb4d07a4f1.0
yarn add @sberdevices/ui@0.20.1-canary.145.a8f010f7e72f4eaf55e848ecd0decccb4d07a4f1.0
```
</details>
> fix(plasma-icons): Icon move className to root obj

- packages/ui/src/components/Header/Header.mdx
- packages/ui/src/components/Header/Header.stories.tsx
- packages/ui/src/components/Header/index.ts
closes: #168 
<details>
<br />
```bash
npm install @sberdevices/ui@0.20.1-canary.169.2f5d0d0c930dd6167ad9ebea22773394da71e7b1.0
yarn add @sberdevices/ui@0.20.1-canary.169.2f5d0d0c930dd6167ad9ebea22773394da71e7b1.0
```
</details>
> fix(ui): Header missing exports

- packages/plasma-icons/src/Icon.assets/Alarm.tsx
- packages/plasma-icons/src/Icon.assets/Call.tsx
- packages/plasma-icons/src/Icon.assets/CallEnd.tsx
- packages/plasma-icons/src/Icon.assets/Play.tsx
С фильтрами иконку не видно под iOS, поболтала с человеком который рисовал, он предположил что это ненужные артефакты
<details>
<br />
```bash
npm install @sberdevices/plasma-icons@0.3.0-canary.207.03aed6bb45b9bbea66f273cd4fcac9fa2cd42d00.0
npm install @sberdevices/ui@0.21.0-canary.207.03aed6bb45b9bbea66f273cd4fcac9fa2cd42d00.0
yarn add @sberdevices/plasma-icons@0.3.0-canary.207.03aed6bb45b9bbea66f273cd4fcac9fa2cd42d00.0
yarn add @sberdevices/ui@0.21.0-canary.207.03aed6bb45b9bbea66f273cd4fcac9fa2cd42d00.0
```
</details>
> feat(plasma-icons): убрать фильтры

- packages/ui/src/components/Typography/Body/index.ts
- packages/ui/src/components/Typography/Button/index.ts
- packages/ui/src/components/Typography/Caption/index.ts
- packages/ui/src/components/Typography/Display/index.ts
- packages/ui/src/components/Typography/Footnote/index.ts
- packages/ui/src/components/Typography/Headline/index.ts
- packages/ui/src/components/Typography/Paragraph/index.ts
- packages/ui/src/components/Typography/Underline/index.ts
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.225.32596c7775c9c0b32c0cbbbaf3b89ef30815c255.0
yarn add @sberdevices/ui@0.21.0-canary.225.32596c7775c9c0b32c0cbbbaf3b89ef30815c255.0
```
</details>
> feat(ui): Добавлено правило переноса строк для типографики

- packages/ui/src/components/Card/index.ts
Задача https://github.com/sberdevices/plasma/issues/81 закрыта, но экспорт возвращен не был
<details>
<br />
```bash
npm install @sberdevices/ui@0.20.1-canary.236.93df47d7029a0356e13836d3e6af3363f63da67e.0
yarn add @sberdevices/ui@0.20.1-canary.236.93df47d7029a0356e13836d3e6af3363f63da67e.0
```
</details>
> fix: Возвращен экспорт CardPrice

- packages/ui/src/components/Image/Image.tsx
- packages/ui/src/components/Image/index.ts
fix: https://github.com/sberdevices/plasma/issues/235
<details>
<br />
```bash
npm install @sberdevices/ui@0.21.0-canary.241.ab0c25ddf0fe2f064ffc0e888838e1b30f53489d.0
yarn add @sberdevices/ui@0.21.0-canary.241.ab0c25ddf0fe2f064ffc0e888838e1b30f53489d.0
```
</details>
> feat(ui): export Ratio type

- packages/ui/src/components/Toast/ToastContext.tsx
- packages/ui/src/components/Toast/ToastProvider.tsx
- packages/ui/src/components/Toast/useToast.ts
Сейчас проблема в том, что:
1. ToastProvider import ToastController
2. ToastController import useToast
3. useToast import ToastProvider (точнее ToastContext из ToastProvider)
Это порождает Circular dependency. Данный PR фиксит эту проблему
<details>
<br />
```bash
npm install @sberdevices/ui@0.20.1-canary.247.e3b4ba10ce7a9269867e1bae9127e6129513e862.0
yarn add @sberdevices/ui@0.20.1-canary.247.e3b4ba10ce7a9269867e1bae9127e6129513e862.0
```
</details>
> fix(plasma-ui): circular dependency

- packages/plasma-core/.gitignore
- packages/plasma-core/package-lock.json
- packages/plasma-core/package.json
- packages/plasma-core/rollup.config.js
- packages/plasma-icons/.gitignore
- packages/plasma-icons/package-lock.json
- packages/plasma-icons/package.json
- packages/plasma-icons/rollup.config.js
- packages/plasma-web/.gitignore
- packages/plasma-web/package-lock.json
- packages/plasma-web/package.json
- packages/plasma-web/rollup.config.js
- packages/ui/.gitignore
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/rollup.config.js
- packages/ui/tsconfig.json
- rollup.config.js
Билд esm и cjs с помощью rollup, а именно tsdx - конфигурация, чтобы ручками много не писать.
Папка dist выглядит так:
dist
├── components
├── hocs
├── hooks
├── index.d.ts
├── index.d.ts.map
├── index.js
├── mixins
├── types
├── ui.cjs.development.js
├── ui.cjs.development.js.map
├── ui.cjs.production.min.js
├── ui.cjs.production.min.js.map
├── ui.esm.js
├── ui.esm.js.map
└── utils
6 directories, 9 files
Обратите внимание:
- оставила старый build (`build:tsc`), чтобы не ломать обратную совместимость. import { Component } from '@sberdevices/ui/long/path'. хотя я бы выпилила, ибо оно не надо, и подняла бы major версию (breaking changes). решение за вами
- есть проблема - при первой установку node_modules (npm i) долго выполняется `build:tsdx` (2-4 мин), последующие норм - ~14 сек, я …
> feat(plasma-ui): esm build

- docs/showcase/src/ui/Image.stories.tsx
- packages/plasma-ui/src/components/Image/Image.stories.tsx
- packages/plasma-ui/src/components/Image/Image.tsx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.6.0-canary.298.a873cb00e80d3d10910fe42b8b2517d12d9c232c.0
npm install @sberdevices/plasma-ui@1.3.0-canary.298.a873cb00e80d3d10910fe42b8b2517d12d9c232c.0
yarn add @sberdevices/showcase@0.6.0-canary.298.a873cb00e80d3d10910fe42b8b2517d12d9c232c.0
yarn add @sberdevices/plasma-ui@1.3.0-canary.298.a873cb00e80d3d10910fe42b8b2517d12d9c232c.0
```
</details>
> feat(ui): Add base to props in Image component

- packages/plasma-icons/package.json
- packages/plasma-ui/package.json
- packages/plasma-web/package.json
fixes: #306 
<details>
<br />
```bash
npm install @sberdevices/showcase@0.7.1-canary.307.cd9cef0fdee7c1dbc07c45cd8a1c24c09c85a277.0
npm install @sberdevices/plasma-icons@1.1.1-canary.307.cd9cef0fdee7c1dbc07c45cd8a1c24c09c85a277.0
npm install @sberdevices/plasma-ui@1.3.1-canary.307.cd9cef0fdee7c1dbc07c45cd8a1c24c09c85a277.0
npm install @sberdevices/plasma-web@1.2.1-canary.307.cd9cef0fdee7c1dbc07c45cd8a1c24c09c85a277.0
yarn add @sberdevices/showcase@0.7.1-canary.307.cd9cef0fdee7c1dbc07c45cd8a1c24c09c85a277.0
yarn add @sberdevices/plasma-icons@1.1.1-canary.307.cd9cef0fdee7c1dbc07c45cd8a1c24c09c85a277.0
yarn add @sberdevices/plasma-ui@1.3.1-canary.307.cd9cef0fdee7c1dbc07c4 …
```
> fix: bump peerDeps

- docs/showcase/src/helpers/TextFieldShowcase.tsx
- packages/plasma-core/src/types/InputHTMLAttributes.ts
- packages/plasma-ui/src/components/TextField/TextField.tsx
- packages/plasma-web/src/components/TextArea/TextArea.tsx
- packages/plasma-web/src/components/TextField/TextField.tsx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.7.2-canary.299.54678e3ddbd5698a9f3bc413de2e5c3743026136.0
npm install @sberdevices/plasma-core@1.1.1-canary.299.54678e3ddbd5698a9f3bc413de2e5c3743026136.0
npm install @sberdevices/plasma-icons@1.1.2-canary.299.54678e3ddbd5698a9f3bc413de2e5c3743026136.0
npm install @sberdevices/plasma-ui@1.3.2-canary.299.54678e3ddbd5698a9f3bc413de2e5c3743026136.0
npm install @sberdevices/plasma-web@1.2.2-canary.299.54678e3ddbd5698a9f3bc413de2e5c3743026136.0
yarn add @sberdevices/showcase@0.7.2-canary.299.54678e3ddbd5698a9f3bc413de2e5c3743026136.0
yarn add @sberdevices/plasma-core@1.1.1-canary.299.54678e3ddbd5698a9f3bc413de2e5c …
```
> fix(plasma-ui): fix setting props in TextField component

- docs/showcase/package.json
- packages/plasma-core/src/components/Badge/Badge.tsx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.9.2-canary.318.5062609e6aa23a5c920306bb15d498a41935c1a2.0
npm install @sberdevices/plasma-core@1.3.2-canary.318.5062609e6aa23a5c920306bb15d498a41935c1a2.0
npm install @sberdevices/plasma-icons@1.3.2-canary.318.5062609e6aa23a5c920306bb15d498a41935c1a2.0
npm install @sberdevices/plasma-ui@1.5.3-canary.318.5062609e6aa23a5c920306bb15d498a41935c1a2.0
npm install @sberdevices/plasma-web@1.4.2-canary.318.5062609e6aa23a5c920306bb15d498a41935c1a2.0
yarn add @sberdevices/showcase@0.9.2-canary.318.5062609e6aa23a5c920306bb15d498a41935c1a2.0
yarn add @sberdevices/plasma-core@1.3.2-canary.318.5062609e6aa23a5c920306bb15d498 …
```
> fix(plasma-core): Badge: fix padding for size s

- packages/plasma-ui/src/components/Carousel/Carousel.stories.tsx
- packages/plasma-ui/src/components/Carousel/Carousel.tsx
I added two new values for the scrollAlign field. "end" which works symmetrically to the "start" value. And "activeDirection", when used, the active element pulls the window behind it, in the direction towards which there is a scroll 
<details>
<br />
```bash
npm install @sberdevices/showcase@0.12.0-canary.317.a27d388d2a8bc3378224367aa478b99f689dead6.0
npm install @sberdevices/plasma-ui@1.8.0-canary.317.a27d388d2a8bc3378224367aa478b99f689dead6.0
yarn add @sberdevices/showcase@0.12.0-canary.317.a27d388d2a8bc3378224367aa478b99f689dead6.0
yarn add @sberdevices/plasma-ui@1.8.0-canary.317.a27d388d2a8bc3378224367aa478b99f689dead6.0
```
</details>
> feat(plasma-ui): Add new scrollAlign values for Carousel

- docs/showcase/src/helpers/CheckboxShowcase.tsx
- docs/showcase/src/helpers/RadioboxShowcase.tsx
- packages/plasma-core/src/components/Basebox/Basebox.tsx
- packages/plasma-ui/src/components/Basebox/Basebox.tsx
- packages/plasma-web/src/components/Checkbox/Checkbox.stories.tsx
- packages/plasma-web/src/components/Radiobox/Radiobox.stories.tsx
Добавил возможность размещения подписи для компонентов Checkbox и Radiobox.
Серый фон для самого активного элемента не нужен, т. к. это цвет карточки внутри которой лежит радиобокс.
<details>
<br />
```bash
npm install @sberdevices/showcase@0.16.0-canary.347.1413cd02f0eb5734c4a83abd5f725f2b0eb132ed.0
npm install @sberdevices/plasma-core@1.8.0-canary.347.1413cd02f0eb5734c4a83abd5f725f2b0eb132ed.0
npm install @sberdevices/plasma-icons@1.9.0-canary.347.1413cd02f0eb5734c4a83abd5f725f2b0eb132ed.0
npm install @sberdevices/plasma-ui@1.12.0-canary.347.1413cd02f0eb5734c4a83abd5f725f2b0eb132ed.0
npm install @sberdevices/plasma-web@1.10.0-canary.347.1413cd02f0eb5734c4a83abd5f725f …
```
> Description for checkbox and radiobox

- packages/plasma-ui/src/components/Card/CardMedia.tsx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.18.1-canary.390.881265e8ce9ea18778d05548637b92a4b4e1824b.0
npm install @sberdevices/plasma-icons@1.11.1-canary.390.881265e8ce9ea18778d05548637b92a4b4e1824b.0
npm install @sberdevices/plasma-ui@1.14.1-canary.390.881265e8ce9ea18778d05548637b92a4b4e1824b.0
npm install @sberdevices/plasma-web@1.12.1-canary.390.881265e8ce9ea18778d05548637b92a4b4e1824b.0
yarn add @sberdevices/showcase@0.18.1-canary.390.881265e8ce9ea18778d05548637b92a4b4e1824b.0
yarn add @sberdevices/plasma-icons@1.11.1-canary.390.881265e8ce9ea18778d05548637b92a4b4e1824b.0
yarn add @sberdevices/plasma-ui@1.14.1-canary.390.881265e8ce9ea18778d05548637 …
```
> fix(plasma-ui): fix simultaneous src&placeholder display

- packages/plasma-tokens/generate.ts
- packages/plasma-tokens/package.json
<details>
<br />
```bash
npm install @sberdevices/showcase@0.21.1-canary.419.9a1f60abeeccd399dfc2bce83a3aef9249f07dab.0
npm install @sberdevices/plasma-tokens@1.5.1-canary.419.9a1f60abeeccd399dfc2bce83a3aef9249f07dab.0
npm install @sberdevices/plasma-ui@1.17.1-canary.419.9a1f60abeeccd399dfc2bce83a3aef9249f07dab.0
npm install @sberdevices/plasma-web@1.15.1-canary.419.9a1f60abeeccd399dfc2bce83a3aef9249f07dab.0
npm install @sberdevices/plasma-tokens-android@2.6.1-canary.419.9a1f60abeeccd399dfc2bce83a3aef9249f07dab.0
npm install @sberdevices/plasma-tokens-ios-swift@2.6.1-canary.419.9a1f60abeeccd399dfc2bce83a3aef9249f07dab.0
yarn add …
```
> fix(plasma-tokens): backward compatibility

- docs/showcase/src/ui/Pickers.stories.tsx
- packages/plasma-core/src/utils/formatters.ts
- packages/plasma-core/src/utils/index.ts
- packages/plasma-ui/src/components/Pickers/DatePicker.tsx
- packages/plasma-ui/src/components/Pickers/Pickers.stories.tsx
- packages/plasma-ui/src/components/Pickers/SimpleDatePicker.tsx
В DatePicker на plasma-ui месяц теперь отображается с коротким названием:
<details>
<br />
```bash
npm install @sberdevices/showcase@0.22.0-canary.392.cb38688a3ec9d39b5bd3af7007297e8336b72df5.0
npm install @sberdevices/plasma-core@1.12.0-canary.392.cb38688a3ec9d39b5bd3af7007297e8336b72df5.0
npm install @sberdevices/plasma-icons@1.15.0-canary.392.cb38688a3ec9d39b5bd3af7007297e8336b72df5.0
npm install @sberdevices/plasma-ui@1.18.0-canary.392.cb38688a3ec9d39b5bd3af7007297e8336b72df5.0
npm install @sberdevices/plasma-web@1.16.0-canary.392.cb38688a3ec9d39b5bd3af7007297e8336b72df5.0
npm install @sberdevices/plasma-tokens-android@2.7.0-canary.392.cb38688a3ec9d39b5bd3af7007297 …
```
> feat: short month name in datepicker

- packages/plasma-core/src/components/Basebox/Basebox.tsx
- packages/plasma-core/src/components/Switch/Switch.tsx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.22.1-canary.338.f5cf3c7c17067c30ac39207fb7d78534b756d444.0
npm install @sberdevices/plasma-core@1.12.1-canary.338.f5cf3c7c17067c30ac39207fb7d78534b756d444.0
npm install @sberdevices/plasma-icons@1.15.1-canary.338.f5cf3c7c17067c30ac39207fb7d78534b756d444.0
npm install @sberdevices/plasma-ui@1.18.1-canary.338.f5cf3c7c17067c30ac39207fb7d78534b756d444.0
npm install @sberdevices/plasma-web@1.16.1-canary.338.f5cf3c7c17067c30ac39207fb7d78534b756d444.0
yarn add @sberdevices/showcase@0.22.1-canary.338.f5cf3c7c17067c30ac39207fb7d78534b756d444.0
yarn add @sberdevices/plasma-core@1.12.1-canary.338.f5cf3c7c17067c30ac39207 …
```
> fix(plasma-core): pass defaultChecked to Switch and Basebox

- packages/plasma-core/package-lock.json
- packages/plasma-core/package.json
- packages/plasma-core/src/mixins/addFocus.ts
<details>
<br />
```bash
npm install @sberdevices/showcase@0.23.1-canary.437.73f888aa2f534f6b3c7533d430b475877b006191.0
npm install @sberdevices/plasma-core@1.12.2-canary.437.73f888aa2f534f6b3c7533d430b475877b006191.0
npm install @sberdevices/plasma-icons@1.16.1-canary.437.73f888aa2f534f6b3c7533d430b475877b006191.0
npm install @sberdevices/plasma-tokens-web@1.5.1-canary.437.73f888aa2f534f6b3c7533d430b475877b006191.0
npm install @sberdevices/plasma-tokens@1.6.1-canary.437.73f888aa2f534f6b3c7533d430b475877b006191.0
npm install @sberdevices/plasma-ui@1.19.1-canary.437.73f888aa2f534f6b3c7533d430b475877b006191.0
npm install …
```
> fix(plasma-core): remove focus on click in button

- packages/plasma-ui/package-lock.json
- packages/plasma-ui/src/components/Pickers/PickerItem.tsx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.26.1-canary.458.9bd2c56123113189405f30d3daa58891527dcccf.0
npm install @sberdevices/plasma-ui@1.22.1-canary.458.9bd2c56123113189405f30d3daa58891527dcccf.0
yarn add @sberdevices/showcase@0.26.1-canary.458.9bd2c56123113189405f30d3daa58891527dcccf.0
yarn add @sberdevices/plasma-ui@1.22.1-canary.458.9bd2c56123113189405f30d3daa58891527dcccf.0
```
</details>
> fix(plasma-ui): PickerItem sizes

- packages/plasma-ui/src/components/Pickers/Pickers.stories.tsx
- packages/plasma-ui/src/components/Pickers/TimePicker.tsx
Исправил отсутсвие примера TimePicker'а во вкладке docs. Добавил выброс исключения при значении вне диапазона для TimePicker'а.
<details>
<br />
```bash
npm install @sberdevices/showcase@0.30.0-canary.516.c45779990b30835669be130c6f1b0c90e476588b.0
npm install @sberdevices/plasma-ui@1.26.0-canary.516.c45779990b30835669be130c6f1b0c90e476588b.0
npm install @sberdevices/plasma-web@1.24.0-canary.516.c45779990b30835669be130c6f1b0c90e476588b.0
npm install @sberdevices/plasma-tokens-android@2.14.0-canary.516.c45779990b30835669be130c6f1b0c90e476588b.0
npm install @sberdevices/plasma-tokens-ios-swift@2.14.0-canary.516.c45779990b30835669be130c6f1b0c90e476588b.0
yarn add …
```
> Plasma UI fix time picker doc

- examples/demo-canvas-app/next.config.js
- examples/demo-canvas-app/pages/test/components/pickers.tsx
- packages/plasma-core/src/components/Carousel/Carousel.tsx
- packages/plasma-core/src/types/ScrollSnap.ts
- packages/plasma-ui/src/components/Pickers/DatePicker.tsx
- packages/plasma-ui/src/components/Pickers/Picker.tsx
- packages/plasma-ui/src/components/Pickers/Pickers.stories.mdx
- packages/plasma-ui/src/components/Pickers/Pickers.stories.tsx
- packages/plasma-ui/src/components/Pickers/SimpleDatePicker.tsx
- packages/plasma-ui/src/components/Pickers/SimpleTimePicker.tsx
- packages/plasma-ui/src/components/Pickers/TimePicker.tsx
Closes #469 
<details>
<br />
```bash
npm install @sberdevices/showcase@0.31.1-canary.527.5c60d9407455719b8f901610ef8f23db832fc4f6.0
npm install @sberdevices/demo-canvas-app@0.3.1-canary.527.5c60d9407455719b8f901610ef8f23db832fc4f6.0
npm install @sberdevices/plasma-core@1.18.1-canary.527.5c60d9407455719b8f901610ef8f23db832fc4f6.0
npm install @sberdevices/plasma-icons@1.23.1-canary.527.5c60d9407455719b8f901610ef8f23db832fc4f6.0
npm install @sberdevices/plasma-ui@1.27.1-canary.527.5c60d9407455719b8f901610ef8f23db832fc4f6.0
npm install @sberdevices/plasma-web@1.25.1-canary.527.5c60d9407455719b8f901610ef8f23db832fc4f6.0
npm install …
```
> fix: Pickers performance, no unnecessary rerender

- examples/demo-canvas-app/pages/_app.tsx
- examples/demo-canvas-app/pages/index.tsx
- examples/demo-canvas-app/pages/test/components/toast.tsx
- packages/plasma-ui/src/components/Fade/Fade.tsx
- packages/plasma-ui/src/components/Toast/Toast.stories.mdx
- packages/plasma-ui/src/components/Toast/Toast.stories.tsx
- packages/plasma-ui/src/components/Toast/ToastController.tsx
Closes #495 
<details>
<br />
```bash
npm install @sberdevices/showcase@0.31.2-canary.528.90276fe6b24b303451dc601816d90e730b065d2b.0
npm install @sberdevices/demo-canvas-app@0.3.2-canary.528.90276fe6b24b303451dc601816d90e730b065d2b.0
npm install @sberdevices/plasma-icons@1.23.2-canary.528.90276fe6b24b303451dc601816d90e730b065d2b.0
npm install @sberdevices/plasma-ui@1.27.2-canary.528.90276fe6b24b303451dc601816d90e730b065d2b.0
npm install @sberdevices/plasma-web@1.25.2-canary.528.90276fe6b24b303451dc601816d90e730b065d2b.0
npm install @sberdevices/plasma-sb-utils@0.8.2-canary.528.90276fe6b24b303451dc601816d90e730b065d2b.0
yarn add …
```
> fix(plasma-ui): Toast fade top placement

- packages/plasma-web/src/components/TextArea/TextArea.tsx
- packages/plasma-web/src/components/TextField/TextField.stories.tsx
- packages/plasma-web/src/components/TextField/TextField.tsx
<details>
<br />
```bash
npm install @sberdevices/showcase@0.31.3-canary.536.5e19a14db10061816f4d988131df10f89b67a2ca.0
npm install @sberdevices/demo-canvas-app@0.3.3-canary.536.5e19a14db10061816f4d988131df10f89b67a2ca.0
npm install @sberdevices/plasma-ui@1.27.3-canary.536.5e19a14db10061816f4d988131df10f89b67a2ca.0
npm install @sberdevices/plasma-web@1.25.3-canary.536.5e19a14db10061816f4d988131df10f89b67a2ca.0
yarn add @sberdevices/showcase@0.31.3-canary.536.5e19a14db10061816f4d988131df10f89b67a2ca.0
yarn add @sberdevices/demo-canvas-app@0.3.3-canary.536.5e19a14db10061816f4d988131df10f89b67a2ca.0
yarn add @sberdevices/plasma-ui@1.27.3-canary.536.5e19a14db10061816f4d988 …
```
> fix(plasma-web): TextField can accept deferred defaultValue

- packages/plasma-web/src/components/Select/SelectView.tsx
`<SelectView>` вызывал submit внутри форм, т.к. дефолтное значение type для `<button>` это submit.
<details>
<br />
```bash
npm install @sberdevices/showcase@0.35.1-canary.557.53bae8d60ce9ee8899e0978f9f4d251300c906bd.0
npm install @sberdevices/plasma-web@1.29.1-canary.557.53bae8d60ce9ee8899e0978f9f4d251300c906bd.0
yarn add @sberdevices/showcase@0.35.1-canary.557.53bae8d60ce9ee8899e0978f9f4d251300c906bd.0
yarn add @sberdevices/plasma-web@1.29.1-canary.557.53bae8d60ce9ee8899e0978f9f4d251300c906bd.0
```
</details>
> fix(plasma-web): form submit trigger inside select

- packages/plasma-ui/src/utils/deviceDetection.ts
Не поддерживалось определение userAgent для ```Mozilla/5.0 (Linux; Android 10; KANT-359 Build/HUAWEIKANT-359; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 Mobile Safari/537.36 ASDK/21.4.2.0 (Android) StarOS/1.71.16 (huawei-tv; Huawei TV)```
<details>
<br />
```bash
npm install @sberdevices/showcase@0.36.1-canary.583.eb4eff21145e2b03ac416482dbc825e32d70678a.0
npm install @sberdevices/demo-canvas-app@0.8.1-canary.583.eb4eff21145e2b03ac416482dbc825e32d70678a.0
npm install @sberdevices/plasma-ui@1.31.1-canary.583.eb4eff21145e2b03ac416482dbc825e32d70678a.0
npm install @sberdevices/plasma-web@1.30.1-canary.583.eb4eff21145e2b03ac416482dbc825e32d …
```
> fix(plasma-ui): huawei detection fix

- packages/plasma-ui/src/components/Badge/Badge.stories.tsx
- packages/plasma-ui/src/components/Button/Button.stories.tsx
- packages/plasma-ui/src/components/Icon/Icon.stories.tsx
- packages/plasma-ui/src/components/Icon/IconSet.tsx
- packages/plasma-ui/src/components/Image/Image.stories.tsx
- packages/plasma-ui/src/helpers/disableProps.tsx
- packages/plasma-ui/src/helpers/index.ts
UI:
+ Badge
+ Button
+ Icon
+ Image
<details>
<br />
```bash
npm install @sberdevices/showcase@0.42.0-canary.627.45dee6832de7942c62c9625b63e4dde665c7bf3c.0
npm install @sberdevices/demo-canvas-app@0.14.0-canary.627.45dee6832de7942c62c9625b63e4dde665c7bf3c.0
npm install @sberdevices/plasma-icons@1.32.0-canary.627.45dee6832de7942c62c9625b63e4dde665c7bf3c.0
npm install @sberdevices/plasma-ui@1.37.0-canary.627.45dee6832de7942c62c9625b63e4dde665c7bf3c.0
npm install @sberdevices/plasma-web@1.36.0-canary.627.45dee6832de7942c62c9625b63e4dde665c7bf3c.0
npm install @sberdevices/plasma-sb-utils@0.16.0-canary.627.45dee6832de7942c62c9625b63e4dde665c7bf3c.0
yarn add …
```
> chore(plasma-ui, plasma-web): knobs to controls migration - part 1

- packages/plasma-web/src/components/Dropdown/Dropdown.stories.tsx
- packages/plasma-web/src/components/Dropdown/Dropdown.types.ts
- packages/plasma-web/src/components/Dropdown/DropdownItem.tsx
- packages/plasma-web/src/components/Dropdown/DropdownList.tsx
- packages/plasma-web/src/components/Select/SelectView.tsx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.22.0-canary.683.68e24f8cb7d88ec7f8445b0e7f70693e6fd07956.0
npm install @sberdevices/plasma-icons@1.39.0-canary.683.68e24f8cb7d88ec7f8445b0e7f70693e6fd07956.0
npm install @sberdevices/plasma-ui@1.45.0-canary.683.68e24f8cb7d88ec7f8445b0e7f70693e6fd07956.0
npm install @sberdevices/plasma-web@1.43.0-canary.683.68e24f8cb7d88ec7f8445b0e7f70693e6fd07956.0
npm install @sberdevices/plasma-sb-utils@0.23.0-canary.683.68e24f8cb7d88ec7f8445b0e7f70693e6fd07956.0
npm install @sberdevices/showcase@0.50.0-canary.683.68e24f8cb7d88ec7f8445b0e7f70693e6fd07956.0
yarn add …
```
> feat: `Dropdown` color, icon; fix: `Dropdown` radius, shadow

- docs/docs/web/components/Tabs.mdx
- packages/plasma-web/src/components/Tabs/TabItem.tsx
- packages/plasma-web/src/components/Tabs/Tabs.stories.tsx
- packages/plasma-web/src/components/Tabs/Tabs.tsx
- packages/plasma-web/src/components/Tabs/TabsContext.tsx
- packages/plasma-web/src/components/Tabs/TabsController.tsx
- packages/plasma-web/src/components/Tabs/index.ts
<details>
<br />
```bash
npm install @sberdevices/plasma-docs@0.1.0-canary.687.5f8b1e9d1c77ab9ade2e51de2ed471ca45a359c9.0
npm install @sberdevices/demo-canvas-app@0.23.0-canary.687.5f8b1e9d1c77ab9ade2e51de2ed471ca45a359c9.0
npm install @sberdevices/plasma-ui@1.46.0-canary.687.5f8b1e9d1c77ab9ade2e51de2ed471ca45a359c9.0
npm install @sberdevices/plasma-web@1.44.0-canary.687.5f8b1e9d1c77ab9ade2e51de2ed471ca45a359c9.0
npm install @sberdevices/extract-sb-docgen-info@0.1.0-canary.687.5f8b1e9d1c77ab9ade2e51de2ed471ca45a359c9.0
npm install @sberdevices/showcase@0.51.0-canary.687.5f8b1e9d1c77ab9ade2e51de2ed471ca45a359c9.0
yarn add …
```
> feat(plasma-web): Added `TabsController` in order to use keyboard arrows

- docs/docs/ui/components/Tabs.mdx
- packages/plasma-core/src/components/Tabs/Tabs.tsx
- packages/plasma-ui/src/components/Tabs/Tabs.stories.tsx
- packages/plasma-ui/src/components/Tabs/Tabs.tsx
<details>
<br />
```bash
npm install @sberdevices/plasma-docs@0.0.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
npm install @sberdevices/demo-canvas-app@0.22.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
npm install @sberdevices/plasma-core@1.27.2-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
npm install @sberdevices/plasma-icons@1.39.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
npm install @sberdevices/plasma-ui@1.45.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
npm install @sberdevices/plasma-web@1.43.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
npm install …
```
> feat(plasma-ui, plasma-core): Added `forwardedAs` and `as` props to `Tabs`

- packages/plasma-ui/src/components/Checkbox/Checkbox.tsx
- packages/plasma-ui/src/components/Radiobox/Radiobox.tsx
- packages/plasma-web/src/components/Checkbox/Checkbox.tsx
<details>
<br />
```bash
npm install @sberdevices/plasma-docs@0.1.3-canary.791.5cbd912667f09ae3819c685b21e62746d3f9a96d.0
npm install @sberdevices/demo-canvas-app@0.23.3-canary.791.5cbd912667f09ae3819c685b21e62746d3f9a96d.0
npm install @sberdevices/plasma-icons@1.39.3-canary.791.5cbd912667f09ae3819c685b21e62746d3f9a96d.0
npm install @sberdevices/plasma-ui@1.46.3-canary.791.5cbd912667f09ae3819c685b21e62746d3f9a96d.0
npm install @sberdevices/plasma-web@1.44.3-canary.791.5cbd912667f09ae3819c685b21e62746d3f9a96d.0
npm install @sberdevices/plasma-sb-utils@0.24.3-canary.791.5cbd912667f09ae3819c685b21e62746d3f9a96d.0
npm install …
```
> fix: Disabled state for `Checkbox` and `Radiobox`

- packages/plasma-ui/src/components/Card/Card.stories.tsx
- packages/plasma-ui/src/components/Card/CardContent.tsx
<details>
<br />
```bash
npm install @sberdevices/plasma-docs@0.2.1-canary.716.4da691138b44ff7d90818a524b1ccf785412f855.0
npm install @sberdevices/demo-canvas-app@0.24.1-canary.716.4da691138b44ff7d90818a524b1ccf785412f855.0
npm install @sberdevices/plasma-tokens-b2c@0.6.1-canary.716.4da691138b44ff7d90818a524b1ccf785412f855.0
npm install @sberdevices/plasma-tokens-web@1.12.1-canary.716.4da691138b44ff7d90818a524b1ccf785412f855.0
npm install @sberdevices/plasma-ui@1.47.1-canary.716.4da691138b44ff7d90818a524b1ccf785412f855.0
npm install @sberdevices/plasma-web@1.45.1-canary.716.4da691138b44ff7d90818a524b1ccf785412f855.0
npm install …
```
> fix(plasma-ui): Added `coverGradient` prop to `CardContent`

- .github/workflows/release.yml
cc @fanisco 
пытаюсь решить проблему падений:
```
found 5424 vulnerabilities (9 low, 1163 moderate, 4252 high)
run `npm audit fix` to fix them, or `npm audit` for details
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@sberdevices%2fplasma-docs-ui - Not found
npm ERR! 404 
npm ERR! 404  '@sberdevices/plasma-docs-ui@0.0.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'plasma-web-docs'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-09-24T10_09_09_019Z-debug.log
lerna ERR! npm i …
```
> ci: fix failing of pkg-locks

- packages/plasma-temple/src/components/Layout/Layout.tsx
- packages/plasma-temple/src/components/Layout/LayoutElementContext.ts
- packages/plasma-temple/src/pages/GridPage/GridPage.tsx
- packages/plasma-temple/src/pages/ItemPage/ItemPage.tsx
Исправил скролл на страницах `GridPage` и `ItemPage`. Проблема была в том, что теперь у нас скролл страницы на элементе `Layout`, а раньше было на `window`.
<details>
<br />
```bash
npm install @sberdevices/plasma-b2c@1.4.1-canary.815.70ea98309f365382c3215538dc4f9716041af1d3.0
npm install @sberdevices/plasma-temple@1.1.2-canary.815.70ea98309f365382c3215538dc4f9716041af1d3.0
npm install @sberdevices/plasma-web@1.49.1-canary.815.70ea98309f365382c3215538dc4f9716041af1d3.0
npm install @sberdevices/showcase@0.56.1-canary.815.70ea98309f365382c3215538dc4f9716041af1d3.0
npm install @sberdevices/plasma-ui-docs@0.6.1-canary.815.70ea98309f365382c3215538dc4f9716041af1d3.0
npm …
```
> fix(plasma-temple): Fix Layout scroll

- packages/plasma-ui/src/components/Pickers/Picker.tsx
- packages/plasma-ui/src/components/Pickers/PickerItem.tsx
- packages/plasma-ui/src/components/Pickers/TimePicker.tsx
- packages/plasma-ui/src/components/Pickers/utils.ts
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.37.1-canary.897.59e60c3025611aeff0ceaafbf7e74146c35da537.0
npm install @sberdevices/plasma-ui@1.60.1-canary.897.59e60c3025611aeff0ceaafbf7e74146c35da537.0
npm install @sberdevices/showcase@0.69.2-canary.897.59e60c3025611aeff0ceaafbf7e74146c35da537.0
npm install @sberdevices/plasma-ui-docs@0.16.2-canary.897.59e60c3025611aeff0ceaafbf7e74146c35da537.0
yarn add @sberdevices/demo-canvas-app@0.37.1-canary.897.59e60c3025611aeff0ceaafbf7e74146c35da537.0
yarn add @sberdevices/plasma-ui@1.60.1-canary.897.59e60c3025611aeff0ceaafbf7e74146c35da537.0
yarn add …
```
> fix(plasma-ui): Fix scroll behavior and range values for `Picker` component

- packages/plasma-web/src/components/Radiobox/Radiobox.tsx
Исправлено сужение радиокнопки
<details>
<br />
```bash
npm install @sberdevices/plasma-b2c@1.16.3-canary.912.8274fd29d2aece8d920c09fad95cd39ae1de0055.0
npm install @sberdevices/plasma-web@1.56.2-canary.912.8274fd29d2aece8d920c09fad95cd39ae1de0055.0
npm install @sberdevices/showcase@0.69.4-canary.912.8274fd29d2aece8d920c09fad95cd39ae1de0055.0
npm install @sberdevices/plasma-ui-docs@0.16.3-canary.912.8274fd29d2aece8d920c09fad95cd39ae1de0055.0
npm install @sberdevices/plasma-web-docs@0.10.2-canary.912.8274fd29d2aece8d920c09fad95cd39ae1de0055.0
npm install @sberdevices/plasma-website@0.4.2-canary.912.8274fd29d2aece8d920c09fad95cd39ae1de0055.0
yarn add …
```
> fix(plasma-web): prevent radiobox elipse shrinking

- packages/plasma-ui/src/components/Pickers/DatePicker.tsx
- packages/plasma-ui/src/components/Pickers/Picker.tsx
- packages/plasma-ui/src/components/Pickers/Pickers.stories.tsx
- packages/plasma-ui/src/components/Pickers/TimePicker.tsx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.39.0-canary.916.2135eb39270b37488dc6dfe3a0db61d58a549dcc.0
npm install @sberdevices/plasma-ui@1.62.0-canary.916.2135eb39270b37488dc6dfe3a0db61d58a549dcc.0
npm install @sberdevices/showcase@0.71.0-canary.916.2135eb39270b37488dc6dfe3a0db61d58a549dcc.0
npm install @sberdevices/plasma-ui-docs@0.18.0-canary.916.2135eb39270b37488dc6dfe3a0db61d58a549dcc.0
yarn add @sberdevices/demo-canvas-app@0.39.0-canary.916.2135eb39270b37488dc6dfe3a0db61d58a549dcc.0
yarn add @sberdevices/plasma-ui@1.62.0-canary.916.2135eb39270b37488dc6dfe3a0db61d58a549dcc.0
yarn add …
```
> feat(plasma-ui): Added option to enable native input for Pickers

- packages/plasma-core/src/components/TextField/TextField.tsx
- packages/plasma-ui/src/components/Field/Field.tsx
- packages/plasma-web/src/components/Field/Field.tsx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.40.1-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
npm install @sberdevices/plasma-b2c@1.18.1-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
npm install @sberdevices/plasma-core@1.35.2-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
npm install @sberdevices/plasma-icons@1.51.2-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
npm install @sberdevices/plasma-ui@1.63.1-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
npm install @sberdevices/plasma-web@1.57.2-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
npm install …
```
> fix: Separate `Input`'s animation by b2b and b2c

- packages/plasma-temple/src/components/Header/Header.tsx
Отдельно `useHeaderProps` нужен при создании кастомных заголовков
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.4.0-canary.902.c99ecafdd3340eca85e00552da2ce876e53d69b1.0
yarn add @sberdevices/plasma-temple@1.4.0-canary.902.c99ecafdd3340eca85e00552da2ce876e53d69b1.0
```
</details>
> feat(plasma-temple): export useHeaderProps

- packages/plasma-web/src/utils/mediaQuery.ts
Для мобилок боковые отступы должны быть 16пх
<details>
<br />
```bash
npm install @sberdevices/plasma-b2c@1.19.1-canary.928.c7afdb42c509c2ff2359d4e5321110da8e2d4337.0
npm install @sberdevices/plasma-web@1.58.1-canary.928.c7afdb42c509c2ff2359d4e5321110da8e2d4337.0
npm install @sberdevices/showcase@0.73.1-canary.928.c7afdb42c509c2ff2359d4e5321110da8e2d4337.0
npm install @sberdevices/plasma-ui-docs@0.21.1-canary.928.c7afdb42c509c2ff2359d4e5321110da8e2d4337.0
npm install @sberdevices/plasma-web-docs@0.13.1-canary.928.c7afdb42c509c2ff2359d4e5321110da8e2d4337.0
npm install @sberdevices/plasma-website@0.8.1-canary.928.c7afdb42c509c2ff2359d4e5321110da8e2d4337.0
yarn add …
```
> fix: plasma-web grid mobile margins

- packages/plasma-b2c/src/components/Slider/Handle.tsx
Уменьшил zIndex у ручки слайдера, чтобы не просвечивал через модальные окна и прочие элементы, очень не удобно прописывать у всех элементов большие zIndex
<details>
<br />
```bash
npm install @sberdevices/plasma-b2c@1.19.2-canary.927.a05be15346f17ce57bbb6a43364b66d053dc423d.0
npm install @sberdevices/showcase@0.73.2-canary.927.a05be15346f17ce57bbb6a43364b66d053dc423d.0
npm install @sberdevices/plasma-website@0.8.2-canary.927.a05be15346f17ce57bbb6a43364b66d053dc423d.0
yarn add @sberdevices/plasma-b2c@1.19.2-canary.927.a05be15346f17ce57bbb6a43364b66d053dc423d.0
yarn add @sberdevices/showcase@0.73.2-canary.927.a05be15346f17ce57bbb6a43364b66d053dc423d.0
yarn add …
```
> fix(plasma-b2c): reduce slider handle z-index

- packages/plasma-web/src/components/Button/Button.stories.tsx
- packages/plasma-web/src/components/Button/Button.tsx
<details>
<br />
```bash
npm install @sberdevices/plasma-b2c@1.20.2-canary.933.904de84dc8edbb263491e61079e0bf5eadddef34.0
npm install @sberdevices/plasma-web@1.59.2-canary.933.904de84dc8edbb263491e61079e0bf5eadddef34.0
npm install @sberdevices/showcase@0.74.2-canary.933.904de84dc8edbb263491e61079e0bf5eadddef34.0
npm install @sberdevices/plasma-ui-docs@0.24.1-canary.933.904de84dc8edbb263491e61079e0bf5eadddef34.0
npm install @sberdevices/plasma-web-docs@0.16.1-canary.933.904de84dc8edbb263491e61079e0bf5eadddef34.0
npm install @sberdevices/plasma-website@0.9.2-canary.933.904de84dc8edbb263491e61079e0bf5eadddef34.0
yarn add …
```
> fix(plasma-web): Add `Button`'s `warning` view

- website/plasma-temple-docs/docs/templates.md
<details>
<br />
```bash
npm install @sberdevices/plasma-b2c@1.20.0-canary.931.4e8074102b7a63849e2fb7d8458b205d31ff54ae.0
npm install @sberdevices/showcase@0.74.0-canary.931.4e8074102b7a63849e2fb7d8458b205d31ff54ae.0
npm install @sberdevices/plasma-website@0.9.0-canary.931.4e8074102b7a63849e2fb7d8458b205d31ff54ae.0
yarn add @sberdevices/plasma-b2c@1.20.0-canary.931.4e8074102b7a63849e2fb7d8458b205d31ff54ae.0
yarn add @sberdevices/showcase@0.74.0-canary.931.4e8074102b7a63849e2fb7d8458b205d31ff54ae.0
yarn add @sberdevices/plasma-website@0.9.0-canary.931.4e8074102b7a63849e2fb7d8458b205d31ff54ae.0
```
</details>
> feat(website): add description for templates docs

- packages/plasma-temple/src/utils/getAssistantSmartAppInitialData.ts
- packages/plasma-temple/src/utils/index.ts
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.7.0-canary.941.11ba7dcb6bdeec8447d73594653870372d840a67.0
yarn add @sberdevices/plasma-temple@1.7.0-canary.941.11ba7dcb6bdeec8447d73594653870372d840a67.0
```
</details>
> feat(plasma-temple): support for window.appInitialData

- packages/plasma-temple/src/pages/ItemPage/ItemPage.tsx
- packages/plasma-temple/src/pages/ItemPage/components/ItemMainSection/ItemMainSection.tsx
Возможность добавить, помимо одной стандартной кнопки, дополнительные кнопки в ItemPage.
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.8.0-canary.938.4a8e0e66c28363ac370221d954157781f4a5368f.0
yarn add @sberdevices/plasma-temple@1.8.0-canary.938.4a8e0e66c28363ac370221d954157781f4a5368f.0
```
</details>
> feat(plasma-temple):  Additional buttons in ItemPage

- packages/plasma-ui/src/components/Stepper/Stepper.stories.tsx
- packages/plasma-ui/src/components/Stepper/Stepper.tsx
- packages/plasma-ui/src/components/Stepper/StepperButton.tsx
- packages/plasma-ui/src/components/Stepper/StepperValue.tsx
- website/plasma-ui-docs/docs/components/Stepper.mdx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.45.0-canary.930.0878aab7d00d478b63ec1f317c600563808c0d93.0
npm install @sberdevices/plasma-ui@1.68.0-canary.930.0878aab7d00d478b63ec1f317c600563808c0d93.0
npm install @sberdevices/showcase@0.77.0-canary.930.0878aab7d00d478b63ec1f317c600563808c0d93.0
npm install @sberdevices/plasma-ui-docs@0.27.0-canary.930.0878aab7d00d478b63ec1f317c600563808c0d93.0
yarn add @sberdevices/demo-canvas-app@0.45.0-canary.930.0878aab7d00d478b63ec1f317c600563808c0d93.0
yarn add @sberdevices/plasma-ui@1.68.0-canary.930.0878aab7d00d478b63ec1f317c600563808c0d93.0
yarn add …
```
> feat(plasma-ui): Add a11y for `Stepper` component

- packages/plasma-b2c/src/components/PreviewGallery/PreviewGallery.tsx
- packages/plasma-b2c/src/components/PreviewGallery/PreviewGalleryItems.tsx
Хочется стилизовать контейнер галереи, а пропсы не прокинуты
<details>
<br />
```bash
npm install @sberdevices/plasma-b2c@1.25.0-canary.965.45f52c0c67c1d2f110a60f3bfa16339b7b7dc0bb.0
npm install @sberdevices/showcase@0.80.0-canary.965.45f52c0c67c1d2f110a60f3bfa16339b7b7dc0bb.0
npm install @sberdevices/plasma-website@0.14.0-canary.965.45f52c0c67c1d2f110a60f3bfa16339b7b7dc0bb.0
yarn add @sberdevices/plasma-b2c@1.25.0-canary.965.45f52c0c67c1d2f110a60f3bfa16339b7b7dc0bb.0
yarn add @sberdevices/showcase@0.80.0-canary.965.45f52c0c67c1d2f110a60f3bfa16339b7b7dc0bb.0
yarn add @sberdevices/plasma-website@0.14.0-canary.965.45f52c0c67c1d2f110a60f3bfa16339b7b7dc0bb.0
``` …
> feat: b2c put preview gallery rest props

- packages/plasma-web/src/components/Select/Select.tsx
- packages/plasma-web/src/components/Select/withMultiSelect.tsx
- packages/plasma-web/src/components/Select/withSingleSelect.tsx
<details>
<br />
```bash
npm install @sberdevices/plasma-b2c@1.26.1-canary.932.54c682715e524eb929a8d6a426f9542d4e8564b0.0
npm install @sberdevices/plasma-web@1.64.1-canary.932.54c682715e524eb929a8d6a426f9542d4e8564b0.0
npm install @sberdevices/showcase@0.81.1-canary.932.54c682715e524eb929a8d6a426f9542d4e8564b0.0
npm install @sberdevices/plasma-ui-docs@0.30.1-canary.932.54c682715e524eb929a8d6a426f9542d4e8564b0.0
npm install @sberdevices/plasma-web-docs@0.21.1-canary.932.54c682715e524eb929a8d6a426f9542d4e8564b0.0
npm install @sberdevices/plasma-website@0.15.1-canary.932.54c682715e524eb929a8d6a426f9542d4e8564b0.0
yarn add …
```
> fix(plama-web): Added possibility to specify a value type in `Select`

- packages/plasma-b2c/src/components/PreviewGallery/PreviewGallery.tsx
- packages/plasma-b2c/src/components/PreviewGallery/PreviewGalleryItems.tsx
Фикс контракта галереи, убрал из пропсов индекс тк он проставляется автоматом
<details>
<br />
```bash
npm install @sberdevices/plasma-b2c@1.27.1-canary.967.1f2c6b20806e6ace8a3ec00fbd7d7ce24b262aef.0
npm install @sberdevices/showcase@0.82.1-canary.967.1f2c6b20806e6ace8a3ec00fbd7d7ce24b262aef.0
npm install @sberdevices/plasma-website@0.16.1-canary.967.1f2c6b20806e6ace8a3ec00fbd7d7ce24b262aef.0
yarn add @sberdevices/plasma-b2c@1.27.1-canary.967.1f2c6b20806e6ace8a3ec00fbd7d7ce24b262aef.0
yarn add @sberdevices/showcase@0.82.1-canary.967.1f2c6b20806e6ace8a3ec00fbd7d7ce24b262aef.0
yarn add @sberdevices/plasma-website@0.16.1-canary.967.1f2c6b20806e6ace8a3ec00fbd7d7ce24b262aef …
```
> fix(palsma-b2c): preview gallery data contracts

- packages/plasma-temple/src/components/MediaPlayer/MediaPlayerTimeline.tsx
- packages/plasma-temple/src/components/MediaPlayer/hooks/useMediaPlayer.ts
- packages/plasma-temple/src/components/VideoPlayer/VideoPlayer.tsx
Исправил обработку значений startTime и endTime для VideoPlayer. Теперь можно передать эти значения и видео будет воспроизводиться только из заданного участка
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.48.1-canary.966.23bf463d3f8961862e4c09bf460dfd29ea9cb6a4.0
npm install @sberdevices/plasma-b2c@1.27.2-canary.966.23bf463d3f8961862e4c09bf460dfd29ea9cb6a4.0
npm install @sberdevices/plasma-core@1.41.1-canary.966.23bf463d3f8961862e4c09bf460dfd29ea9cb6a4.0
npm install @sberdevices/plasma-icons@1.58.1-canary.966.23bf463d3f8961862e4c09bf460dfd29ea9cb6a4.0
npm install @sberdevices/plasma-temple@1.10.1-canary.966.23bf463d3f8961862e4c09bf460dfd29ea9cb6a4 …
```
> fix(plasma-temple): Fix time chop in VideoPlayer

- packages/plasma-temple/src/components/VideoPlayer/VideoPlayer.tsx
Теперь контролы у плеера появляются при нажатии клавиш. Исправление проблемы с тем, что нельзя вызвать контролы нажатием кнопок на пульте.
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.14.1-canary.989.6c47e3c40672600af02987037c40102b20e687c5.0
yarn add @sberdevices/plasma-temple@1.14.1-canary.989.6c47e3c40672600af02987037c40102b20e687c5.0
```
</details>
> fix(plasma-temple): Always show player controls on key press

- packages/plasma-temple/src/components/Page/Page.tsx
Исправление проблемы с вычислением ширины контейнера при асинхронной загрузке страницы (lazy import) 
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.15.1-canary.995.ebd4cd4c2ca4b0506ed4abbb1fe12a156c7806c4.0
yarn add @sberdevices/plasma-temple@1.15.1-canary.995.ebd4cd4c2ca4b0506ed4abbb1fe12a156c7806c4.0
```
</details>
> fix(plasma-temple): Fix async Layout render

- packages/plasma-temple/src/components/MediaPlayer/MediaPlayerControls.tsx
- packages/plasma-temple/src/components/VideoPlayer/VideoPlayer.tsx
- packages/plasma-temple/src/pages/VideoPage/VideoPage.tsx
Добавил возможность скрывать контролы в `VideoPlayer`. Плюс добавил ref для `MediaPlayerControls`.
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.16.0-canary.1011.f071ff3b9fa133242bc3e14b4f976d5c84478560.0
yarn add @sberdevices/plasma-temple@1.16.0-canary.1011.f071ff3b9fa133242bc3e14b4f976d5c84478560.0
```
</details>
> feat(plasma-temple): Ability to hide player controls

- packages/plasma-ui/src/components/Header/HeaderArrow.tsx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.52.1-canary.1016.4eaa3bc9c9203f268fa09b8ede6b062621a22ded.0
npm install @sberdevices/plasma-temple@1.17.1-canary.1016.4eaa3bc9c9203f268fa09b8ede6b062621a22ded.0
npm install @sberdevices/plasma-ui@1.75.1-canary.1016.4eaa3bc9c9203f268fa09b8ede6b062621a22ded.0
npm install @sberdevices/showcase@0.88.1-canary.1016.4eaa3bc9c9203f268fa09b8ede6b062621a22ded.0
npm install @sberdevices/plasma-ui-docs@0.35.1-canary.1016.4eaa3bc9c9203f268fa09b8ede6b062621a22ded.0
yarn add @sberdevices/demo-canvas-app@0.52.1-canary.1016.4eaa3bc9c9203f268fa09b8ede6b062621a22ded.0
yarn add …
```
> fix(plasma-ui): Set `HeaderArrow` full height

- packages/plasma-temple/src/components/VideoPlayer/VideoPlayer.tsx
- packages/plasma-temple/src/pages/VideoPage/VideoPage.tsx
Добавил возможность контролировать `object-fit` для элемента `video` в `VideoPage`
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.18.0-canary.1023.a05aac37ab97da30bddb63a215805dd6990919d2.0
yarn add @sberdevices/plasma-temple@1.18.0-canary.1023.a05aac37ab97da30bddb63a215805dd6990919d2.0
```
</details>
> feat(plasma-temple): Controlled video fit on video page

- packages/plasma-temple/src/components/Page/types.ts
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.19.3-canary.1040.c836fd76759391a983286bd827c209fe4d99b0f1.0
yarn add @sberdevices/plasma-temple@1.19.3-canary.1040.c836fd76759391a983286bd827c209fe4d99b0f1.0
```
</details>
> fix(plasma-temple): Don't pass page name to PageMethods

- packages/plasma-temple/src/components/MediaPlayer/hooks/useMediaPlayer.ts
Для `useMediaPlayer`, сделал обновление в реальном времени значения `currentTime`. Кажется, что по умолчанию мы должны отдавать правильное значение `currentTime`, а не значение, которое было на момент последнего обновления состояния. Если есть возражения, то можно сделать возможность настройки этого поведения.
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.21.1-canary.1050.07819cd8bd7278bf6f478a8c88eb1ae099ed5824.0
yarn add @sberdevices/plasma-temple@1.21.1-canary.1050.07819cd8bd7278bf6f478a8c88eb1ae099ed5824.0
```
</details>
> fix(plasma-temple): Realtime update for currentTime in useMediaPlayer

- packages/plasma-ui/src/components/Button/ActionButton.tsx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.54.1-canary.1045.d0577854b72aa4f189200dd348a61b81b5836e36.0
npm install @sberdevices/plasma-temple@1.22.1-canary.1045.d0577854b72aa4f189200dd348a61b81b5836e36.0
npm install @sberdevices/plasma-ui@1.77.1-canary.1045.d0577854b72aa4f189200dd348a61b81b5836e36.0
npm install @sberdevices/showcase@0.91.1-canary.1045.d0577854b72aa4f189200dd348a61b81b5836e36.0
npm install @sberdevices/plasma-ui-docs@0.38.1-canary.1045.d0577854b72aa4f189200dd348a61b81b5836e36.0
yarn add @sberdevices/demo-canvas-app@0.54.1-canary.1045.d0577854b72aa4f189200dd348a61b81b5836e36.0
yarn add …
```
> fix(plasma-ui): `ActionButton`: Made `pin` not required again

- packages/plasma-temple/src/components/MediaPlayer/hooks/useMediaPlayer.ts
Исправление проблемы с тем, что видео иногда не воспроизводится после смены дорожки
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.24.1-canary.1036.0388c7ccc4489ff3414b73c90fda72a234c45386.0
yarn add @sberdevices/plasma-temple@1.24.1-canary.1036.0388c7ccc4489ff3414b73c90fda72a234c45386.0
```
</details>
> fix(plasma-temple): don't stop video on source change

- packages/plasma-core/src/components/Basebox/Basebox.tsx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.55.1-canary.1056.77d2ec501ae5353903277ebd497c588d6d37815c.0
npm install @sberdevices/plasma-b2c@1.37.1-canary.1056.77d2ec501ae5353903277ebd497c588d6d37815c.0
npm install @sberdevices/plasma-core@1.48.1-canary.1056.77d2ec501ae5353903277ebd497c588d6d37815c.0
npm install @sberdevices/plasma-icons@1.65.1-canary.1056.77d2ec501ae5353903277ebd497c588d6d37815c.0
npm install @sberdevices/plasma-temple@1.24.3-canary.1056.77d2ec501ae5353903277ebd497c588d6d37815c.0
npm install @sberdevices/plasma-ui@1.78.1-canary.1056.77d2ec501ae5353903277ebd497c588d6d37815c.0
npm install …
```
> fix(plasma-core): Add inherit cursor in label for `BaseBox` component

- actions/versionate-docs/src/main.ts
- website/plasma-temple-docs/docusaurus.config.js
- website/plasma-ui-docs/docusaurus.config.js
- website/plasma-ui-docs/versionsArchived.json
- website/plasma-web-docs/docusaurus.config.js
<details>
<br />
```bash
npm install @sberdevices/versionate-docs@0.1.1-canary.1062.46c2c971e915b79be6703f228e584a9f1e277ffa.0
npm install @sberdevices/plasma-b2c@1.38.1-canary.1062.46c2c971e915b79be6703f228e584a9f1e277ffa.0
npm install @sberdevices/plasma-temple@1.25.1-canary.1062.46c2c971e915b79be6703f228e584a9f1e277ffa.0
npm install @sberdevices/plasma-web@1.74.1-canary.1062.46c2c971e915b79be6703f228e584a9f1e277ffa.0
npm install @sberdevices/showcase@0.93.1-canary.1062.46c2c971e915b79be6703f228e584a9f1e277ffa.0
npm install @sberdevices/plasma-temple-docs@0.4.2-canary.1062.46c2c971e915b79be6703f228e584a9f1e277ffa.0
npm install …
```
> fix: Docs base url via env VERSION_NAME

- packages/plasma-b2c/package.json
- packages/plasma-core/package.json
- packages/plasma-icons/package.json
- packages/plasma-temple/package.json
- packages/plasma-typo/package.json
- packages/plasma-ui/package.json
- packages/plasma-web/package.json
- utils/plasma-cy-utils/package.json
- utils/plasma-sb-utils/package.json
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.57.1-canary.1053.bb84e31e66c83a73ad444b32404084bcf51f87d5.0
npm install @sberdevices/plasma-b2c@1.39.1-canary.1053.bb84e31e66c83a73ad444b32404084bcf51f87d5.0
npm install @sberdevices/plasma-core@1.49.1-canary.1053.bb84e31e66c83a73ad444b32404084bcf51f87d5.0
npm install @sberdevices/plasma-icons@1.67.1-canary.1053.bb84e31e66c83a73ad444b32404084bcf51f87d5.0
npm install @sberdevices/plasma-temple@1.26.1-canary.1053.bb84e31e66c83a73ad444b32404084bcf51f87d5.0
npm install @sberdevices/plasma-typo@0.2.2-canary.1053.bb84e31e66c83a73ad444b32404084bcf51f87d5.0
npm install …
```
> [plasma-*]: fix typings peer deps versions

- packages/plasma-web/src/components/TextField/TextField.tsx
<details>
<br />
```bash
npm install @sberdevices/plasma-b2c@1.39.3-canary.1073.628a58536e7f27c3a4aae03f14e33035d42d878d.0
npm install @sberdevices/plasma-temple@1.27.3-canary.1073.628a58536e7f27c3a4aae03f14e33035d42d878d.0
npm install @sberdevices/plasma-web@1.75.3-canary.1073.628a58536e7f27c3a4aae03f14e33035d42d878d.0
npm install @sberdevices/showcase@0.95.2-canary.1073.628a58536e7f27c3a4aae03f14e33035d42d878d.0
npm install @sberdevices/plasma-ui-docs@0.42.2-canary.1073.628a58536e7f27c3a4aae03f14e33035d42d878d.0
npm install @sberdevices/plasma-web-docs@0.32.3-canary.1073.628a58536e7f27c3a4aae03f14e33035d42d878d.0
npm install …
```
> fix(plasma-web): `TextField`: fix `size:l` by providing $size to input

- packages/plasma-temple/src/components/HeroSlider/HeroSlider@common.tsx
- packages/plasma-temple/src/components/HeroSlider/types.ts
Возможность передавать `initialIndex` в `HeroSlider`
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.28.0-canary.1078.d371710cf1a2758754c0c5e8eaf8be63504c556d.0
yarn add @sberdevices/plasma-temple@1.28.0-canary.1078.d371710cf1a2758754c0c5e8eaf8be63504c556d.0
```
</details>
> feat(plasma-temple): Config initial index in HeroSlider

- packages/plasma-temple/src/components/HeroSlide/HeroSlide.tsx
- packages/plasma-temple/src/components/HeroSlider/HeroSlider@common.tsx
- packages/plasma-temple/src/components/HeroSlider/types.ts
Возможность отключить автофокус в `HeroSlider`
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.29.0-canary.1077.3ab858da764e1ebee82d28be545a6d46944c55f6.0
yarn add @sberdevices/plasma-temple@1.29.0-canary.1077.3ab858da764e1ebee82d28be545a6d46944c55f6.0
```
</details>
> feat(plasma-temple): Ability to disable autofocus in HeroSlider

- packages/plasma-core/src/components/Carousel/Carousel.tsx
- packages/plasma-web/src/components/Carousel/Carousel.tsx
- packages/plasma-web/src/components/Carousel/index.ts
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.59.2-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
npm install @sberdevices/plasma-b2c@1.41.1-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
npm install @sberdevices/plasma-core@1.49.6-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
npm install @sberdevices/plasma-icons@1.67.7-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
npm install @sberdevices/plasma-temple@1.31.1-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
npm install @sberdevices/plasma-ui@1.82.2-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
npm install …
```
> fix(plasma-web): `Carousel`: moved style resets to core

- packages/plasma-temple/src/components/MediaPlayer/hooks/useMediaPlayer.ts
- packages/plasma-temple/src/components/VideoPlayer/VideoPlayer.tsx
Исправление проставления classname для постера при переключении видео
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.35.1-canary.1132.b268fd8a0a2739c0b915169676744434cf237f1f.0
npm install @sberdevices/plasma-temple-docs@0.7.1-canary.1132.b268fd8a0a2739c0b915169676744434cf237f1f.0
yarn add @sberdevices/plasma-temple@1.35.1-canary.1132.b268fd8a0a2739c0b915169676744434cf237f1f.0
yarn add @sberdevices/plasma-temple-docs@0.7.1-canary.1132.b268fd8a0a2739c0b915169676744434cf237f1f.0
```
</details>
> fix(plasma-temple): Poster classname on video change

- website/plasma-web-docs/docusaurus.config.js
<details>
<br />
```bash
npm install @sberdevices/plasma-web-docs@0.36.1-canary.1138.fa6b2a407f0f5071d6622ee76ea121527c78c520.0
yarn add @sberdevices/plasma-web-docs@0.36.1-canary.1138.fa6b2a407f0f5071d6622ee76ea121527c78c520.0
```
</details>
> fix(plasma-web-docs): Docusaurus docgen plugin's json fail

- packages/plasma-temple/src/hooks/index.ts
Экспорт для `useSpatNavBetweenTargets`
<details>
<br />
```bash
npm install @sberdevices/plasma-temple@1.43.0-canary.1140.5cdddf9630e499a17e740147871770cf43afcf51.0
yarn add @sberdevices/plasma-temple@1.43.0-canary.1140.5cdddf9630e499a17e740147871770cf43afcf51.0
```
</details>
> feat(plasma-temple): Export for useSpatNavBetweenTargets

- packages/plasma-ui/src/components/Pickers/Pickers.stories.tsx
<details>
<br />
```bash
npm install @sberdevices/demo-canvas-app@0.71.0-canary.1181.97ab37ed19d78de85eb6c6037f236f87d4261533.0
npm install @sberdevices/plasma-temple@1.53.0-canary.1181.97ab37ed19d78de85eb6c6037f236f87d4261533.0
npm install @sberdevices/plasma-ui@1.94.0-canary.1181.97ab37ed19d78de85eb6c6037f236f87d4261533.0
npm install @sberdevices/showcase@0.114.0-canary.1181.97ab37ed19d78de85eb6c6037f236f87d4261533.0
npm install @sberdevices/plasma-ui-docs@0.63.0-canary.1181.97ab37ed19d78de85eb6c6037f236f87d4261533.0
yarn add @sberdevices/demo-canvas-app@0.71.0-canary.1181.97ab37ed19d78de85eb6c6037f236f87d4261533.0
yarn add …
```
> feat(plasma-ui): Add keys for `Pickers` components in stories
